"""Williams WPC-era game database.

Each entry describes a MAME ROM zip we know how to extract.  The
``game_roms`` list is filename patterns to match against contained
``.rom`` files inside the zip; ``sound_roms`` lists DCS audio file
names; and ``filename_hints`` is substrings checked against the
zip's basename when ROM-file matching is ambiguous.  Detection
scores each game by hit count and picks the winner.

The supported set is the wpcedit.js author's confirmed list — every
title here uses the same WPC font / graphics / animation master-
table layout that our :mod:`.wpc_decode` port understands.  More
WPC titles can be added by appending entries; detection is data-
driven, so no code change is needed.

Generations:

  * **WPC**       — early WPC (Funhouse-era), 1990–1991.
                    Most "no DMD" games in this era are excluded —
                    they use an alphanumeric display, not a DMD.
  * **WPC-S**     — WPC with security PIC, 1995.
  * **WPC-95**    — final WPC iteration, 1995–1999.
  * **WPC-DCS**   — DCS digital sound system overlay on WPC core,
                    1993–1994 (Fish Tales era).

We don't currently distinguish these generations in the pipeline —
the master-table format is the same across all of them — but the
``platform`` field is preserved for reference.
"""

GAME_DB = {
    # ----- WPC-DCS (1992-1993) -----
    "fish_tales": {
        "display": "Fish Tales",
        "manufacturer": "Williams",
        "year": 1992,
        "platform": "WPC-DCS",
        "game_roms": ["fshtl_5.rom", "fish_tl5.rom", "ft_l5.rom"],
        "sound_roms": ["ft_u18.l1", "ft_u14.l1", "ft_u15.l1"],
        "filename_hints": ["ft_l", "ft_p", "fshtl", "fish_tl"],
    },
    "white_water": {
        "display": "White Water",
        "manufacturer": "Williams",
        "year": 1993,
        "platform": "WPC-DCS",
        "game_roms": ["ww_lh6.rom", "ww_lh5.rom", "ww_l5.rom"],
        "sound_roms": ["ww_u14.l1", "ww_u15.l1", "ww_u18.l1"],
        "filename_hints": ["ww_lh", "ww_l", "wwater"],
    },
    "twilight_zone": {
        "display": "Twilight Zone",
        "manufacturer": "Bally",
        "year": 1993,
        "platform": "WPC-DCS",
        "game_roms": ["tz_94h.rom", "tz_92.rom", "tz_h8.rom",
                      "tz_pa1.rom"],
        "sound_roms": ["tzu14.l1", "tzu15.l1", "tzu18.l1"],
        "filename_hints": ["tz_92", "tz_94", "tz_h", "tz_pa", "tz_p"],
    },
    "indiana_jones": {
        "display": "Indiana Jones",
        "manufacturer": "Williams",
        "year": 1993,
        "platform": "WPC-DCS",
        "game_roms": ["ij_l7.rom", "ij_l6.rom", "ij_l5.rom", "ij_l3.rom"],
        "sound_roms": ["ij_u14.l1", "ij_u15.l1", "ij_u18.l1"],
        "filename_hints": ["ij_l"],
    },
    "judge_dredd": {
        "display": "Judge Dredd",
        "manufacturer": "Bally",
        "year": 1993,
        "platform": "WPC-DCS",
        "game_roms": ["jd_l7.rom", "jd_l6.rom", "jd_l5.rom", "jd_l1.rom"],
        "sound_roms": ["jd_u14.l1", "jd_u15.l1", "jd_u18.l1"],
        "filename_hints": ["jd_l"],
    },
    "star_trek_tng": {
        "display": "Star Trek: The Next Generation",
        "manufacturer": "Williams",
        "year": 1993,
        "platform": "WPC-DCS",
        "game_roms": ["sttng_l7.rom", "sttng_l5.rom", "sttng_lx7.rom",
                      "sttng_x7.rom"],
        "sound_roms": ["sttng_u14.l1", "sttng_u15.l1", "sttng_u18.l1"],
        "filename_hints": ["sttng_l", "sttng_p", "sttng_lx", "sttng_x"],
    },

    # ----- WPC-Fliptronics II / DCS (1993-1994) -----
    "addams_family": {
        "display": "The Addams Family",
        "manufacturer": "Bally",
        "year": 1992,
        "platform": "WPC",
        "game_roms": ["addamf_l7.rom", "addam_l5.rom", "addam_lp4.rom",
                      "addams_p2.rom", "tafg_lx3.rom"],
        "sound_roms": ["af_u14.l1", "af_u15.l1", "af_u18.l1"],
        "filename_hints": ["addam", "af_l", "afg_", "tafg"],
    },
    "creature_black_lagoon": {
        "display": "Creature from the Black Lagoon",
        "manufacturer": "Bally",
        "year": 1992,
        "platform": "WPC",
        "game_roms": ["cftbl_l4.rom", "cftbl_l3.rom", "cftbl_l2.rom"],
        "sound_roms": ["cf_u14.l1", "cf_u15.l1", "cf_u18.l1"],
        "filename_hints": ["cftbl"],
    },
    "doctor_who": {
        "display": "Doctor Who",
        "manufacturer": "Bally",
        "year": 1992,
        "platform": "WPC",
        "game_roms": ["dw_l2.rom", "dw_l1.rom"],
        "sound_roms": ["dw_u14.l1", "dw_u15.l1", "dw_u18.l1"],
        "filename_hints": ["dw_l"],
    },
    "dr_dredd": {
        "display": "Dirty Harry",
        "manufacturer": "Williams",
        "year": 1995,
        "platform": "WPC-S",
        "game_roms": ["dh_lx2.rom"],
        "sound_roms": ["dhsndl1.512", "dh_u14.l1", "dh_u15.l1", "dh_u18.l1"],
        "filename_hints": ["dh_lx", "dh_l"],
    },
    "bram_stokers_dracula": {
        "display": "Bram Stoker's Dracula",
        "manufacturer": "Williams",
        "year": 1993,
        "platform": "WPC-Fliptronics II",
        "game_roms": ["drac_l1.rom", "drac_l2c.rom", "drac_lx1.rom"],
        "sound_roms": ["drac_u14.l1", "drac_u15.l1", "drac_u18.l1"],
        "filename_hints": ["drac_l"],
    },
    "demolition_man": {
        "display": "Demolition Man",
        "manufacturer": "Williams",
        "year": 1994,
        "platform": "WPC-DCS",
        "game_roms": ["dm_lx4.rom", "dm_lx3.rom", "dm_h6.rom", "dm_h5.rom"],
        "sound_roms": ["dm_u14.l1", "dm_u15.l1", "dm_u18.l1"],
        "filename_hints": ["dm_l", "dm_h"],
    },
    "flintstones": {
        "display": "The Flintstones",
        "manufacturer": "Williams",
        "year": 1994,
        "platform": "WPC-Security",
        "game_roms": ["flin_lx5.rom", "flin_lx4.rom", "flin_lx3.rom",
                      "flin_lx2.rom", "fs_lx5.rom"],
        "sound_roms": ["fs_u2_s.l1", "fs_u3_s.l1", "fs_u4_s.l1",
                       "fs_u5_s.l1", "fs_u6_s.l1", "fs_u7_s.l1",
                       "fs_u8_s.l1", "fs_u9_s.l1",
                       "fs_u14.l1", "fs_u15.l1", "fs_u18.l1"],
        "filename_hints": ["fs_lx", "fs_l", "flin"],
    },
    "popeye": {
        "display": "Popeye Saves the Earth",
        "manufacturer": "Bally",
        "year": 1994,
        "platform": "WPC-Fliptronics II",
        "game_roms": ["popeye_lx5.rom", "pop_lx5.rom", "pop_lx4.rom",
                      "pop_la4.rom"],
        "sound_roms": ["popeye_u14.l1", "pop_u14.l1", "pop_u15.l1",
                       "pop_u18.l1"],
        "filename_hints": ["pop_l", "popeye"],
    },
    "world_cup_soccer": {
        "display": "World Cup Soccer",
        "manufacturer": "Bally",
        "year": 1994,
        "platform": "WPC-DCS",
        "game_roms": ["wcs_lx2.rom", "wcs_l2.rom", "wcs_p2.rom"],
        "sound_roms": ["wcs_u14.l1", "wcs_u15.l1", "wcs_u18.l1"],
        "filename_hints": ["wcs_l", "wcs_p"],
    },
    "hurricane": {
        "display": "Hurricane",
        "manufacturer": "Williams",
        "year": 1991,
        "platform": "WPC",
        "game_roms": ["hurri_l2.rom", "hurr_l2.rom"],
        "sound_roms": ["hurr_u14.l1", "hurr_u15.l1", "hurr_u18.l1"],
        "filename_hints": ["hurr"],
    },
    "black_rose": {
        "display": "Black Rose",
        "manufacturer": "Bally",
        "year": 1992,
        "platform": "WPC",
        "game_roms": ["br_l3.rom", "br_l4.rom", "br_l1.rom"],
        "sound_roms": ["br_u14.l1", "br_u15.l1", "br_u18.l1"],
        "filename_hints": ["br_l"],
    },
    "gilligans_island": {
        "display": "Gilligan's Island",
        "manufacturer": "Bally",
        "year": 1991,
        "platform": "WPC",
        "game_roms": ["gi_l9.rom", "gi_l8.rom", "gi_l6.rom", "gi_l4.rom",
                      "gi_l3.rom"],
        "sound_roms": ["gi_u14.l1", "gi_u15.l1", "gi_u18.l1"],
        "filename_hints": ["gi_l"],
    },
    "the_getaway": {
        "display": "The Getaway: High Speed II",
        "manufacturer": "Williams",
        "year": 1992,
        "platform": "WPC",
        "game_roms": ["gw_l5.rom", "gw_l3.rom", "gw_l2.rom", "gw_l1.rom"],
        "sound_roms": ["gw_u14.l1", "gw_u15.l1", "gw_u18.l1"],
        "filename_hints": ["gw_l"],
    },
    "terminator_2": {
        "display": "Terminator 2: Judgment Day",
        "manufacturer": "Williams",
        "year": 1991,
        "platform": "WPC",
        "game_roms": ["t2_l8.rom", "t2_l6.rom", "t2_l4.rom", "t2_l3.rom"],
        "sound_roms": ["t2_u14.l1", "t2_u15.l1", "t2_u18.l1"],
        "filename_hints": ["t2_l"],
    },
    "slugfest": {
        "display": "SlugFest",
        "manufacturer": "Williams",
        "year": 1991,
        "platform": "WPC",
        "game_roms": ["slugfest_l1.rom", "slug_l1.rom"],
        "sound_roms": ["slug_u14.l1", "slug_u15.l1", "slug_u18.l1"],
        "filename_hints": ["slug"],
    },

    # ----- WPC-S (Security, 1995) -----
    "no_fear": {
        "display": "No Fear: Dangerous Sports",
        "manufacturer": "Williams",
        "year": 1995,
        "platform": "WPC-S",
        "game_roms": ["nofe2_3x.rom", "nofe2_3.rom", "nf_23x.rom"],
        "sound_roms": ["nfu2s", "nfu3s", "nfu4s", "nfu5s", "nfu6s", "nfu7s"],
        "filename_hints": ["nofe", "nf_2", "nofear"],
    },
    "indianapolis_500": {
        "display": "Indianapolis 500",
        "manufacturer": "Bally",
        "year": 1995,
        "platform": "WPC-S",
        "game_roms": ["i500_11r.rom", "i500_10r.rom", "indy500_11r.rom"],
        "sound_roms": ["i500_u14.l1", "i500_u15.l1", "i500_u18.l1"],
        "filename_hints": ["i500_", "indy500"],
    },
    "who_dunnit": {
        "display": "Who Dunnit",
        "manufacturer": "Bally",
        "year": 1995,
        "platform": "WPC-S",
        "game_roms": ["wd_l2.rom", "wd_12r.rom", "wd_12s.rom"],
        "sound_roms": ["wd_u14.l1", "wd_u15.l1", "wd_u18.l1"],
        "filename_hints": ["wd_l", "wd_1"],
    },
    "jackbot": {
        "display": "Jack*Bot",
        "manufacturer": "Williams",
        "year": 1995,
        "platform": "WPC-S",
        "game_roms": ["jb_10r.rom", "jb_10b.rom", "jb_101r.rom"],
        "sound_roms": ["jb_u14.l1", "jb_u15.l1", "jb_u18.l1"],
        "filename_hints": ["jb_1", "jb_10"],
    },
    "shadow": {
        "display": "The Shadow",
        "manufacturer": "Bally",
        "year": 1994,
        "platform": "WPC-S",
        "game_roms": ["shadow_lx6.rom", "shadow_l6.rom", "shadow_lx3.rom"],
        "sound_roms": ["shadow_u14.l1", "shadow_u15.l1", "shadow_u18.l1"],
        "filename_hints": ["shadow_l", "shadow_lx"],
    },
    "corvette": {
        "display": "Corvette",
        "manufacturer": "Bally",
        "year": 1994,
        "platform": "WPC-S",
        "game_roms": ["corv_lx2.rom", "corv_lx1.rom", "corv_21.rom"],
        "sound_roms": ["corv_u14.l1", "corv_u15.l1", "corv_u18.l1"],
        "filename_hints": ["corv_l", "corv_2"],
    },
    "congo": {
        "display": "Congo",
        "manufacturer": "Williams",
        "year": 1995,
        "platform": "WPC-S",
        "game_roms": ["congo_21.rom", "congo_20.rom", "congo_11.rom"],
        "sound_roms": ["congo_u14.l1", "congo_u15.l1", "congo_u18.l1"],
        "filename_hints": ["congo_"],
    },
    "roadshow": {
        "display": "Red & Ted's Road Show",
        "manufacturer": "Williams",
        "year": 1994,
        "platform": "WPC-Security",
        "game_roms": ["rs_l6.rom", "rs_lx5.rom", "rs_lx4.rom", "rs_lx3.rom",
                      "rs_la4.rom"],
        "sound_roms": ["rs_u14.l1", "rs_u15.l1", "rs_u18.l1"],
        "filename_hints": ["rs_l", "rs_lx", "rs_la"],
    },

    # ----- WPC-95 (1995-1999) -----
    "theatre_of_magic": {
        "display": "Theatre of Magic",
        "manufacturer": "Bally",
        "year": 1995,
        "platform": "WPC-95",
        "game_roms": ["tom_14h.rom", "tom_14.rom", "tom_13.rom", "tom_06.rom"],
        "sound_roms": ["tom_s2.rom", "tom_s3.rom", "tom_s4.rom",
                       "tom_s5.rom"],
        "filename_hints": ["tom_1", "tom_06"],
    },
    "attack_from_mars": {
        "display": "Attack From Mars",
        "manufacturer": "Bally",
        "year": 1995,
        "platform": "WPC-95",
        "game_roms": ["afm_113b.bin", "afm_113.bin", "afm_113b.rom",
                      "afm_113.rom", "afm_11.rom", "afm_10.rom"],
        "sound_roms": ["afm_s2.l1", "afm_s3.l1", "afm_s4.l1", "afm_s5.l1",
                       "afm_s2.rom", "afm_s3.rom", "afm_s4.rom",
                       "afm_s5.rom"],
        "filename_hints": ["afm_1"],
    },
    "scared_stiff": {
        "display": "Scared Stiff",
        "manufacturer": "Bally",
        "year": 1996,
        "platform": "WPC-95",
        "game_roms": ["ss_15.rom", "ss_12.rom", "ss_11.rom", "ss_03.rom"],
        "sound_roms": ["ss_s2.rom", "ss_s3.rom", "ss_s4.rom", "ss_s5.rom"],
        "filename_hints": ["ss_1", "ss_0"],
    },
    "junkyard": {
        "display": "Junk Yard",
        "manufacturer": "Williams",
        "year": 1996,
        "platform": "WPC-95",
        "game_roms": ["jy_12.rom", "jy_11.rom"],
        "sound_roms": ["jy_s2.rom", "jy_s3.rom", "jy_s4.rom", "jy_s5.rom"],
        "filename_hints": ["jy_1"],
    },
    "tales_of_arabian_nights": {
        "display": "Tales of the Arabian Nights",
        "manufacturer": "Williams",
        "year": 1996,
        "platform": "WPC-95",
        "game_roms": ["totan_14.rom", "totan_13.rom", "totan_12.rom"],
        "sound_roms": ["totan_s2.rom", "totan_s3.rom", "totan_s4.rom",
                       "totan_s5.rom"],
        "filename_hints": ["totan_1"],
    },
    "safe_cracker": {
        "display": "Safe Cracker",
        "manufacturer": "Bally",
        "year": 1996,
        "platform": "WPC-95",
        "game_roms": ["sc_18g.rom", "sc_18.rom", "sc_17.rom", "sc_14.rom"],
        "sound_roms": ["sc_s2.rom", "sc_s3.rom", "sc_s4.rom", "sc_s5.rom"],
        "filename_hints": ["sc_1", "scrack"],
    },
    "nba_fastbreak": {
        "display": "NBA Fastbreak",
        "manufacturer": "Bally",
        "year": 1997,
        "platform": "WPC-95",
        "game_roms": ["nbaf_31.rom", "nbaf_21.rom", "nbaf_115.rom",
                      "nbaf_11.rom"],
        "sound_roms": ["nbaf_s2.rom", "nbaf_s3.rom", "nbaf_s4.rom",
                       "nbaf_s5.rom"],
        "filename_hints": ["nbaf_"],
    },
    "no_good_gofers": {
        "display": "No Good Gofers",
        "manufacturer": "Williams",
        "year": 1997,
        "platform": "WPC-95",
        "game_roms": ["ngg_13.rom", "ngg_12.rom", "ngg_10.rom"],
        "sound_roms": ["ngg_s2.rom", "ngg_s3.rom", "ngg_s4.rom",
                       "ngg_s5.rom"],
        "filename_hints": ["ngg_1"],
    },
    "medieval_madness": {
        "display": "Medieval Madness",
        "manufacturer": "Williams",
        "year": 1997,
        "platform": "WPC-95",
        "game_roms": ["mm_109c.rom", "mm_109.rom", "mm_10.rom", "mm_05.rom"],
        "sound_roms": ["mm_s2.rom", "mm_s3.rom", "mm_s4.rom", "mm_s5.rom"],
        "filename_hints": ["mm_1", "mm_0"],
    },
    "cirqus_voltaire": {
        "display": "Cirqus Voltaire",
        "manufacturer": "Bally",
        "year": 1997,
        "platform": "WPC-95",
        "game_roms": ["cv_20h.rom", "cv_20.rom", "cv_14.rom", "cv_13.rom",
                      "cv_11.rom", "cv_10.rom"],
        "sound_roms": ["cv_s2.rom", "cv_s3.rom", "cv_s4.rom", "cv_s5.rom"],
        "filename_hints": ["cv_2", "cv_1"],
    },
    "champion_pub": {
        "display": "The Champion Pub",
        "manufacturer": "Bally",
        "year": 1998,
        "platform": "WPC-95",
        "game_roms": ["cp_16.rom", "cp_15.rom"],
        "sound_roms": ["cp_s2.rom", "cp_s3.rom", "cp_s4.rom", "cp_s5.rom"],
        "filename_hints": ["cp_1"],
    },
    "monster_bash": {
        "display": "Monster Bash",
        "manufacturer": "Williams",
        "year": 1998,
        "platform": "WPC-95",
        "game_roms": ["mb_106.rom", "mb_10.rom", "mb_05.rom"],
        "sound_roms": ["mb_s2.rom", "mb_s3.rom", "mb_s4.rom", "mb_s5.rom"],
        "filename_hints": ["mb_1", "mb_0"],
    },
    "cactus_canyon": {
        "display": "Cactus Canyon",
        "manufacturer": "Bally",
        "year": 1998,
        "platform": "WPC-95",
        "game_roms": ["cc_13.rom", "cc_12.rom", "cc_10.rom"],
        "sound_roms": ["cc_s2.rom", "cc_s3.rom", "cc_s4.rom", "cc_s5.rom"],
        "filename_hints": ["cc_1"],
    },

    # ----- Misc Williams WPC (no DMD games excluded) -----
    "johnny_mnemonic": {
        "display": "Johnny Mnemonic",
        "manufacturer": "Williams",
        "year": 1995,
        "platform": "WPC-S",
        "game_roms": ["jm_12r.rom", "jm_12b.rom", "jm_05r.rom"],
        "sound_roms": ["jm_u14.l1", "jm_u15.l1", "jm_u18.l1"],
        "filename_hints": ["jm_1", "jm_0"],
    },
    "ticket_tac_toe": {
        "display": "Ticket Tac Toe",
        "manufacturer": "Bally",
        "year": 1996,
        "platform": "WPC-95",
        "game_roms": ["tikt1_0.rom", "ttt_10.rom"],
        "sound_roms": ["ttt_s2.rom", "ttt_s3.rom"],
        "filename_hints": ["ttt_1", "tikt"],
    },
}
