#!/usr/bin/env python3
"""mktables.py - build a title's playfield tables FROM THE TITLE, not from git.

    mktables.py                          # whatever run_game.sh published
    mktables.py --game godzilla_pro
    mktables.py --log ~/gzwatch.log --wait 30
    mktables.py --force                  # rebuild even if they look current

Writes into `$PAD_TABLES/<title>/` (padpath.py decides where that is):

    playfield.png     the title's own artwork, copied out of its assets
    device_xy.txt     every switch, coil and LED with a position   (devicexy.py)
    led_io.txt        the insert map, node and index               (ledio.py)
    switch_list.txt   id, num, node, bit, name                     (swtable.py)
    switch_xy.txt     switch id -> position, joined on the name    (switchxy.py)

WHY THIS EXISTS. All five used to be generated by hand, once, and COMMITTED -
and only for Godzilla Pro, so every other title got a schematic and it read like
a property of the title rather than of the repository. They are derived data:
the artwork is the game's own `assets/nuk/images/Test/*_playfield.png`, and
every coordinate in every table comes out of the device table in the game ELF.
A card image has all of it. So it is built when a title is first run and cached,
and nothing about a title needs to be added to git for that title to work.

THREE OF THE FIVE NEED NO RUN AT ALL, and that is worth knowing because it is
what lets the window open with artwork, inserts and coils the very first time a
title boots. device_xy comes from the ELF; led_io is derived entirely from
device_xy (ledio.py's wire enumeration contributes no column - it agrees or it
disagrees); the artwork is a file copy.

THE SWITCH TABLES ARE THE EXCEPTION AND CANNOT BE MADE ONE. The game builds its
switch table on the HEAP at run time - that is why the shim hunts for it by
shape - so the id belonging to a name is not in the binary anywhere. It reaches
the outside world only as the shim's `[sw]` dump in the run log. Hence --log and
--wait: on the FIRST run of a title the switches arrive a few seconds after the
game starts, and on every run after that they come from this cache instantly.

WHAT IS DELIBERATELY NOT DONE HERE: nothing is ever written back into the
checkout, and no table is written into a title's own directory. A card is opened
read only and stays that way.
"""
import argparse
import os
import re
import shutil
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import devicexy
import gameinfo
import ledio
import padpath
import swtable
import switchxy

#: The header the shim prints before the switch dump, and the line it prints
#: immediately after it. Both are needed: `count=` alone tells you a dump has
#: STARTED, and a table read halfway through is a table with holes in it.
SW_HEADER = re.compile(r"\[sw\] --- switches: count=(\d+)")
SW_FOOTER = "[dev] --- ball devices:"

#: How often to look at the log while waiting. The dump is a few hundred lines
#: written in one go, so there is nothing to be gained by looking faster.
POLL_S = 0.5


def _read(path):
    try:
        with open(path, "rb") as f:
            return f.read().decode("latin-1")
    except OSError:
        return ""


def switch_dump_complete(log_path):
    """Whether `log_path` holds a switch dump that has FINISHED.

    Reading one that is still being written yields a short table, and a short
    switch table is not visibly wrong - it just silently loses the switches at
    the end of the list. So the footer is required, not just the header.
    """
    text = _read(log_path)
    m = None
    for m in SW_HEADER.finditer(text):
        pass
    if not m:
        return False
    return SW_FOOTER in text[m.end():]


def wait_for_switches(log_path, timeout_s, say=None):
    """Wait for the shim to dump the switch table. True if it arrived.

    Bounded on purpose. A title whose table the shim cannot find never dumps,
    and the right answer then is a playfield with artwork and no clickable
    switches, not a window that never opens.
    """
    if not log_path or timeout_s <= 0:
        return False
    deadline = time.time() + timeout_s
    told = False
    while time.time() < deadline:
        if switch_dump_complete(log_path):
            return True
        if say and not told:
            say("waiting up to %ds for the game to publish its switch table"
                % int(timeout_s))
            told = True
        time.sleep(POLL_S)
    return False


def _stale(dest, source):
    """Whether `dest` needs rebuilding against `source`."""
    if not os.path.exists(dest):
        return True
    if not source or not os.path.exists(source):
        return False               # nothing to compare against; keep what we have
    try:
        return os.path.getmtime(dest) < os.path.getmtime(source)
    except OSError:
        return True


def _write(path, text):
    d = os.path.dirname(os.path.abspath(path))
    if not os.path.isdir(d):
        os.makedirs(d)
    with open(path, "w", newline="") as f:     # newline='': LF even on Windows
        f.write(text)


def build(game=None, log_path=None, wait_s=0, force=False, say=print):
    """Build every table this title can have. Returns what was written.

    Never raises for a missing part: a title with no artwork, or one whose
    switch table never appeared, gets what it CAN have and the caller is told
    what is missing. Refusing to write anything because one input is absent is
    how the whole window used to be skipped in silence.
    """
    game = gameinfo.active(game)
    if not game:
        say("no active title - set PAD_GAME, or start a run")
        return {}

    tdir = gameinfo.table_dir(game)
    if not tdir:
        say("no table directory - PAD_ROOT/PAD_TABLES point nowhere")
        return {}
    if not os.path.isdir(tdir):
        os.makedirs(tdir)

    made, elf = {}, gameinfo.elf(game)
    say("title %s -> %s" % (game, tdir))

    # --- the artwork -----------------------------------------------------
    # Copied rather than referenced. On a card run the assets are on a
    # read-only FUSE mount that the playfield window - a WINDOWS process
    # reaching in over \\wsl.localhost - may not be able to open at all, and
    # the window must not depend on that working.
    art_dest = os.path.join(tdir, "playfield.png")
    art_src = gameinfo.find_playfield_art(game)
    if art_src and (force or not os.path.exists(art_dest)):
        try:
            shutil.copyfile(art_src, art_dest)
            made["playfield.png"] = art_dest
            say("  artwork      %s" % os.path.basename(art_src))
        except OSError as e:
            say("  artwork      FAILED: %s" % e)
    elif os.path.exists(art_dest):
        say("  artwork      (cached)")
    else:
        # Not a fault. TMNT 1.59 ships no images/Test at all, which is why the
        # window has a schematic mode in the first place.
        say("  artwork      none - this title ships no playfield drawing")

    # --- device positions, and the LED map derived from them -------------
    dev_dest = os.path.join(tdir, "device_xy.txt")
    led_dest = os.path.join(tdir, "led_io.txt")
    recs = None
    if force or _stale(dev_dest, elf) or _stale(led_dest, elf):
        if not elf or not os.path.exists(elf):
            say("  devices      no game binary at %s" % elf)
        else:
            try:
                recs = devicexy.build(game)
            except (OSError, SystemExit) as e:
                say("  devices      FAILED: %s" % e)
                recs = None
    if recs is not None:
        pf_w, pf_h = devicexy.playfield_size(game)
        _write(dev_dest, devicexy.text(game, recs, art_src, pf_w, pf_h))
        made["device_xy.txt"] = dev_dest
        counts = devicexy.counts(recs)
        if not recs:
            # A REAL ANSWER, not a failure, and it must not be dressed up as
            # one: TMNT 1.59 ships no device table at all - no images/Test, and
            # "playfield" appears in its binary only in adjustment help text.
            # The empty file is what stops this being re-derived every run.
            say("  devices      none - this title ships no device table, so the "
                "playfield is a schematic")
        else:
            say("  devices      %d records (%s)"
                % (len(recs),
                   " ".join("%s=%d" % kv for kv in sorted(counts.items()))))
            # The self-checks RUN on every build - see devicexy.checks() for
            # what each one caught. They are printed, never swallowed: a table
            # that is one field out parses perfectly and draws a confident
            # wrong picture. Not printed for an empty table, where they would
            # be three lines of zeros claiming a check had happened.
            for line in devicexy.checks(recs, pf_w, pf_h):
                say("               %s" % line)

        rows, _problems, _report = ledio.build(recs, None)
        _write(led_dest, ledio.text(game, rows, False))
        made["led_io.txt"] = led_dest
        if rows:
            say("  inserts      %d LEDs" % len(rows))
    else:
        say("  devices      (cached)" if os.path.exists(dev_dest)
            else "  devices      MISSING - the playfield will be a schematic")

    # --- the switch table, which is the only part that needs a run -------
    sw_list = os.path.join(tdir, "switch_list.txt")
    sw_xy = os.path.join(tdir, "switch_xy.txt")
    if os.path.exists(sw_list) and not force:
        say("  switches     (cached)")
    else:
        if log_path and not switch_dump_complete(log_path):
            wait_for_switches(log_path, wait_s,
                              say=lambda m: say("  switches     %s" % m))
        if not log_path or not switch_dump_complete(log_path):
            say("  switches     no switch dump yet - clickable switches will "
                "appear on the next run of this title")
            return made
        live_rows = swtable.read(log_path)
        if not live_rows:
            say("  switches     the dump is there but held no rows")
            return made
        _write(sw_list, swtable.text(game, live_rows))
        made["switch_list.txt"] = sw_list
        say("  switches     %d in the game's own table" % len(live_rows))

    # --- positions, which NO LONGER need a run (item 27) -----------------
    #
    # This join used to run off the live dump's names, inside the branch
    # above - two bugs in one place. First, a title whose switch_list was
    # cached before switch_xy existed took the (cached) early-return forever,
    # so the join never ran again and the playfield drew coils and no
    # switches (Jaws, David, 2026-08-10: "why aren't the switch locations on
    # the virtual playfield?"). Second, the LIVE names are msg_row()'s, which
    # answer `?` on every title whose message-table address resolves wrong -
    # jaws, led_zeppelin, elvira - which is precisely why swnames.py fills
    # switch_list.txt from the DEVICE table instead. So join from the on-disk
    # list swnames has already named, and no run is involved at all.
    if (force or not os.path.exists(sw_xy)) and os.path.exists(sw_list):
        if recs is None and os.path.exists(dev_dest):
            try:
                recs = devicexy.build(game)
            except (OSError, SystemExit):
                recs = None
        if recs:
            names = switchxy.read_list(sw_list)
            joined = switchxy.join(names, recs)
            if joined:
                _write(sw_xy, switchxy.text(game, joined))
                made["switch_xy.txt"] = sw_xy
                say("  positions    %d switches placed on the artwork"
                    % len(joined))
            else:
                # Real and worth saying out loud: it means the two tables
                # share no names - a title whose device table names things
                # differently, or a list that is still all `?`.
                say("  positions    NONE of the %d named switches matched a "
                    "device-table name" % len(names))
    return made


def drawable(game=None):
    """Whether this title has enough to draw a playfield WITHOUT a run.

    The caller that matters is watch.sh, and the decision it makes with this is
    the difference between a useful first run and a useless one:

      * yes - artwork or device positions exist, so open the window NOW and
        finish the switch tables behind it. The window shows the playfield,
        its inserts and its coils immediately, and gains clickable switches on
        the next run of that title.
      * no  - there is nothing to draw at all until the game publishes its
        switch list, so waiting for it is the only way the window is worth
        opening. Led Zeppelin and Elvira are this case: no images/Test and no
        device table anywhere in the binary.
    """
    game = gameinfo.active(game)
    if not game:
        return False
    tdir = gameinfo.table_dir(game)
    if not tdir:
        return False
    art = os.path.join(tdir, "playfield.png")
    if os.path.exists(art):
        return True
    dev = os.path.join(tdir, "device_xy.txt")
    try:
        with open(dev) as f:
            return any(not ln.startswith("#") and ln.strip() for ln in f)
    except OSError:
        return False


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--game", default=None, help="title (default: the active one)")
    ap.add_argument("--log", default=None, help="a run log to read the switch table from")
    ap.add_argument("--wait", type=float, default=0,
                    help="seconds to wait for the switch dump to appear")
    ap.add_argument("--force", action="store_true", help="rebuild everything")
    a = ap.parse_args()
    made = build(a.game, a.log, a.wait, a.force)
    if not made:
        print("nothing written")
    # A machine-readable last line, so watch.sh can decide whether to open the
    # playfield window now or wait for the switch table first.
    print("drawable=%s" % ("yes" if drawable(a.game) else "no"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
