#!/usr/bin/env python3
"""mktables.py - build a title's playfield tables FROM THE TITLE, not from git.

    mktables.py                          # whatever run_game.sh published
    mktables.py --game godzilla_pro
    mktables.py --log ~/gzwatch.log --wait 30
    mktables.py --force                  # rebuild even if they look current

Writes into `$PAD_TABLES/<title>/` (padpath.py decides where that is):

    playfield.png     the title's own artwork, copied out of its assets
    device_xy.txt     every switch, coil and LED with a position   (devicexy.py)
    led_io.txt        the insert map, node and index               (ledio.py)
    switch_list.txt   id, num, node, bit, name                     (swtable.py)
    switch_xy.txt     switch id -> position, joined on the name    (switchxy.py)

WHY THIS EXISTS. All five used to be generated by hand, once, and COMMITTED -
and only for Godzilla Pro, so every other title got a schematic and it read like
a property of the title rather than of the repository. They are derived data:
the artwork is the game's own `assets/nuk/images/Test/*_playfield.png`, and
every coordinate in every table comes out of the device table in the game ELF.
A card image has all of it. So it is built when a title is first run and cached,
and nothing about a title needs to be added to git for that title to work.

THREE OF THE FIVE NEED NO RUN AT ALL, and that is worth knowing because it is
what lets the window open with artwork, inserts and coils the very first time a
title boots. device_xy comes from the ELF; led_io is derived entirely from
device_xy (ledio.py's wire enumeration contributes no column - it agrees or it
disagrees); the artwork is a file copy.

THE SWITCH TABLES ARE THE EXCEPTION AND CANNOT BE MADE ONE. The game builds its
switch table on the HEAP at run time - that is why the shim hunts for it by
shape - so the id belonging to a name is not in the binary anywhere. It reaches
the outside world only as the shim's `[sw]` dump in the run log. Hence --log and
--wait: on the FIRST run of a title the switches arrive a few seconds after the
game starts, and on every run after that they come from this cache instantly.

WHAT IS DELIBERATELY NOT DONE HERE: nothing is ever written back into the
checkout, and no table is written into a title's own directory. A card is opened
read only and stays that way.
"""
import argparse
import os
import re
import shutil
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import devicexy
import gameinfo
import ledio
import padpath
import swelf
import swnames
import swtable
import switchxy

#: The header the shim prints before the switch dump, and the line it prints
#: immediately after it. Both are needed: `count=` alone tells you a dump has
#: STARTED, and a table read halfway through is a table with holes in it.
SW_HEADER = re.compile(r"\[sw\] --- switches: count=(\d+)")
SW_FOOTER = "[dev] --- ball devices:"

#: How often to look at the log while waiting. The dump is a few hundred lines
#: written in one go, so there is nothing to be gained by looking faster.
POLL_S = 0.5


def _read(path):
    try:
        with open(path, "rb") as f:
            return f.read().decode("latin-1")
    except OSError:
        return ""


def switch_dump_complete(log_path):
    """Whether `log_path` holds a switch dump that has FINISHED.

    Reading one that is still being written yields a short table, and a short
    switch table is not visibly wrong - it just silently loses the switches at
    the end of the list. So the footer is required, not just the header.
    """
    text = _read(log_path)
    m = None
    for m in SW_HEADER.finditer(text):
        pass
    if not m:
        return False
    return SW_FOOTER in text[m.end():]


def wait_for_switches(log_path, timeout_s, say=None):
    """Wait for the shim to dump the switch table. True if it arrived.

    Bounded on purpose. A title whose table the shim cannot find never dumps,
    and the right answer then is a playfield with artwork and no clickable
    switches, not a window that never opens.
    """
    if not log_path or timeout_s <= 0:
        return False
    deadline = time.time() + timeout_s
    told = False
    while time.time() < deadline:
        if switch_dump_complete(log_path):
            return True
        if say and not told:
            say("waiting up to %ds for the game to publish its switch table"
                % int(timeout_s))
            told = True
        time.sleep(POLL_S)
    return False


def _stale(dest, source):
    """Whether `dest` needs rebuilding against `source`."""
    if not os.path.exists(dest):
        return True
    if not source or not os.path.exists(source):
        return False               # nothing to compare against; keep what we have
    try:
        return os.path.getmtime(dest) < os.path.getmtime(source)
    except OSError:
        return True


def _read_list(path):
    """[(id, num, node, bit, name)] from an on-disk switch_list.txt, or []."""
    rows = []
    try:
        with open(path) as f:
            for line in f:
                if line.startswith("#"):
                    continue
                fields = line.split(None, 4)
                if len(fields) >= 5:
                    rows.append((int(fields[0]), int(fields[1]),
                                 int(fields[2]), int(fields[3]),
                                 fields[4].strip()))
    except (OSError, ValueError):
        return []
    return rows


#: The header devicexy.text() writes naming the binary a table came from.
BINARY_TAG = "# binary: "


def _recorded_binary(dest):
    """What `dest` says it was built from, or None if it does not say."""
    try:
        with open(dest) as f:
            for line in f:
                if not line.startswith("#"):
                    return None            # past the header, nothing found
                if line.startswith(BINARY_TAG):
                    return line[len(BINARY_TAG):].strip()
    except OSError:
        return None
    return None


def _built_from(dest, source):
    """Whether `dest` records having come from the binary that is there NOW.

    ★ MTIME ALONE SAID YES TO SEVENTEEN FILES IT SHOULD HAVE REFUSED
    (2026-08-21). _stale() above is the whole cache test, and it compares two
    timestamps. Both of its answers were wrong here in the same way:

      * A TABLE BUILT WITH NO BINARY AT ALL still counts as newer than one.
        The item 57 catalogue sweep ran over every title in the cache, and for
        the ones whose card was not mounted it wrote a device_xy.txt holding
        zero records - which is indistinguishable, to a timestamp, from the
        legitimate empty that a title with no device table gets, and which the
        code above deliberately keeps so the table is not re-derived every run.
        17 of 30 cached titles were carrying one, `godzilla_le` among them, and
        nothing was ever going to rebuild them: the empty file WAS the cache.

      * A CARD'S FILES CARRY THE IMAGE'S MTIMES, NOT THE COPY'S. godzilla_le's
        binary on the card reads Jul 28; the empty table built from nothing
        reads Aug 19. The table is "newer" than a binary it never opened, so a
        DIFFERENT card for the same title is invisible here too.

    So the identity of the source is written INTO the table (devicexy.text) and
    checked here. A table that names no binary was built without one and is
    rebuilt; a table naming a different one is rebuilt; the legitimate empty
    names its binary, matches, and stays cached exactly as before.
    """
    if not os.path.exists(dest):
        return True                # _stale() already answers this one
    if not source or not os.path.exists(source):
        return True                # nothing to compare against; keep what we have
    return _recorded_binary(dest) == devicexy.binary_id(source)


def _write(path, text):
    """Write ATOMICALLY - tmp in the same dir, then replace (item 49).

    Two 2-second pollers latch PERMANENTLY on their first successful parse of
    exactly these files: padglhost's binds_resolve (switch_list.txt) and the
    playfield's poll_for_tables. binds_export in padglhost.c states the rule
    for a polled file - tmp+rename, "must never parse half of one" - and this
    producer did not follow it: a reader could catch the file mid-write and
    commit to the head of it for the whole run. The same shape also meant a
    write that failed AFTER open() (disk full, a kill mid-write) left a
    truncated destination that the exists-means-cached check upstream then
    trusted on every later run. With the replace, the destination either does
    not exist or is whole; a stray .tmp is harmless and overwritten next
    time."""
    d = os.path.dirname(os.path.abspath(path))
    if not os.path.isdir(d):
        os.makedirs(d)
    tmp = path + ".tmp"
    with open(tmp, "w", newline="") as f:      # newline='': LF even on Windows
        f.write(text)
    os.replace(tmp, path)


def build(game=None, log_path=None, wait_s=0, force=False, say=print):
    """Build every table this title can have. Returns what was written.

    Never raises for a missing part: a title with no artwork, or one whose
    switch table never appeared, gets what it CAN have and the caller is told
    what is missing. Refusing to write anything because one input is absent is
    how the whole window used to be skipped in silence.
    """
    game = gameinfo.active(game)
    if not game:
        say("no active title - set PAD_GAME, or start a run")
        return {}

    tdir = gameinfo.table_dir(game)
    if not tdir:
        say("no table directory - PAD_ROOT/PAD_TABLES point nowhere")
        return {}
    if not os.path.isdir(tdir):
        os.makedirs(tdir)

    made, elf = {}, gameinfo.elf(game)
    say("title %s -> %s" % (game, tdir))

    # --- the artwork -----------------------------------------------------
    # Copied rather than referenced. On a card run the assets are on a
    # read-only FUSE mount that the playfield window - a WINDOWS process
    # reaching in over \\wsl.localhost - may not be able to open at all, and
    # the window must not depend on that working.
    art_dest = os.path.join(tdir, "playfield.png")
    art_src = gameinfo.find_playfield_art(game)
    if art_src and (force or not os.path.exists(art_dest)):
        try:
            shutil.copyfile(art_src, art_dest)
            made["playfield.png"] = art_dest
            say("  artwork      %s" % os.path.basename(art_src))
        except OSError as e:
            say("  artwork      FAILED: %s" % e)
    elif os.path.exists(art_dest):
        say("  artwork      (cached)")
    else:
        # Not a fault. TMNT 1.59 ships no images/Test at all, which is why the
        # window has a schematic mode in the first place.
        say("  artwork      none - this title ships no playfield drawing")

    # --- device positions, and the LED map derived from them -------------
    dev_dest = os.path.join(tdir, "device_xy.txt")
    led_dest = os.path.join(tdir, "led_io.txt")
    recs = None
    if (force or _stale(dev_dest, elf) or _stale(led_dest, elf)
            or not _built_from(dev_dest, elf)):
        if not elf or not os.path.exists(elf):
            say("  devices      no game binary at %s" % elf)
        else:
            try:
                recs = devicexy.build(game)
            except (OSError, SystemExit) as e:
                say("  devices      FAILED: %s" % e)
                recs = None
    if recs is not None:
        pf_w, pf_h = devicexy.playfield_size(game)
        # Named failure, not a traceback (item 49): an uncaught raise here
        # kills main() BEFORE the drawable= line prints, and watch.sh then
        # routes a title with perfectly good artwork into its "nothing to
        # draw yet" branch. Same class as the switch write below.
        try:
            _write(dev_dest,
                   devicexy.text(game, recs, art_src, pf_w, pf_h, elf))
        except OSError as exc:
            say("  devices      FAILED to write %s: %s" % (dev_dest, exc))
            recs = None
    if recs is not None:
        made["device_xy.txt"] = dev_dest
        counts = devicexy.counts(recs)
        if not recs:
            # A REAL ANSWER, not a failure, and it must not be dressed up as
            # one: TMNT 1.59 ships no device table at all - no images/Test, and
            # "playfield" appears in its binary only in adjustment help text.
            # The empty file is what stops this being re-derived every run.
            say("  devices      none - this title ships no device table, so the "
                "playfield is a schematic")
        else:
            say("  devices      %d records (%s)"
                % (len(recs),
                   " ".join("%s=%d" % kv for kv in sorted(counts.items()))))
            # The self-checks RUN on every build - see devicexy.checks() for
            # what each one caught. They are printed, never swallowed: a table
            # that is one field out parses perfectly and draws a confident
            # wrong picture. Not printed for an empty table, where they would
            # be three lines of zeros claiming a check had happened.
            for line in devicexy.checks(recs, pf_w, pf_h):
                say("               %s" % line)

        rows, _problems, _report = ledio.build(recs, None)
        try:
            _write(led_dest, ledio.text(game, rows, False))
            made["led_io.txt"] = led_dest
            if rows:
                say("  inserts      %d LEDs" % len(rows))
        except OSError as exc:
            say("  inserts      FAILED to write %s: %s" % (led_dest, exc))
    else:
        say("  devices      (cached)" if os.path.exists(dev_dest)
            else "  devices      MISSING - the playfield will be a schematic")

    # --- the switch table, which is the only part that needs a run -------
    sw_list = os.path.join(tdir, "switch_list.txt")
    sw_xy = os.path.join(tdir, "switch_xy.txt")
    repaired = False
    if os.path.exists(sw_list) and not force:
        # ★ REPAIR A CACHED LIST WHOSE NAMES ARE STILL `?`. The dump branch
        # below used to write the shim's rows as-is, and on a title whose
        # message-table address resolves wrong (item 29) that is every name -
        # beatles' first run cached 92/92 `?`, so binds_resolve matched no
        # flipper, switchxy joined nothing, and the miss was PERMANENT: an
        # existing file is exactly what this branch trusts. So a cached list
        # is re-asked here through the same swnames fill the write path now
        # uses; a list it cannot improve is left alone, and a list with the
        # game's own names never has one replaced (swnames' own rule).
        rows = _read_list(sw_list)
        if any(r[4] == "?" for r in rows):
            filled, _report = swnames.fill(rows, game, elf)
            if filled != rows:
                try:
                    _write(sw_list, swtable.text(game, filled))
                    repaired = True
                    made["switch_list.txt"] = sw_list
                    # "filled", not "from the device table": on a title whose
                    # device table cannot be read the fill is platform labels
                    # alone, and a log line naming the wrong source is worse
                    # than one naming none (the NB_WHY lesson in watch.sh).
                    say("  switches     (cached) - filled %d of its %d `?` "
                        "names (swnames: device table + platform labels)"
                        % (sum(1 for a, b in zip(rows, filled)
                               if a[4] != b[4]), len(rows)))
                except OSError as exc:
                    say("  switches     FAILED to repair %s: %s"
                        % (sw_list, exc))
            else:
                say("  switches     (cached; %d `?` names the device table "
                    "cannot fill)" % sum(1 for r in rows if r[4] == "?"))
        else:
            say("  switches     (cached)")
    else:
        if log_path and not switch_dump_complete(log_path):
            wait_for_switches(log_path, wait_s,
                              say=lambda m: say("  switches     %s" % m))
        if not log_path or not switch_dump_complete(log_path):
            # ★ THE RUN IS NOT ALWAYS COMING. The docstring above says the
            # switch tables "cannot" be built without a run because the game
            # builds its table on the heap - true of Godzilla Pro, and false of
            # stranger_things_le, whose table is static and whose shape the
            # shim's by-shape hunt can never match (44-byte entries carrying
            # neither node nor bit; see swelf.py). For a title like that,
            # "appear on the next run" was a promise this code could not keep,
            # and the playfield window sat on "No tables yet" for ever.
            elf_rows = []
            if elf and os.path.exists(elf):
                try:
                    elf_rows = swelf.rows(elf, game)
                except (OSError, SystemExit):
                    elf_rows = []
            if elf_rows:
                live_rows = elf_rows
                sw_src = "read out of the game's binary, no run needed"
            else:
                say("  switches     no switch dump yet - clickable switches "
                    "will appear on the next run of this title")
                return made
        else:
            live_rows = swtable.read(log_path)
            sw_src = "from the shim's dump"
            if not live_rows:
                say("  switches     the dump is there but held no rows")
                return made
        # FILL THE `?` NAMES BEFORE THE LIST EVER TOUCHES DISK. The shim
        # reads names through a per-title message-table address that resolves
        # wrong on most titles (item 29), and this writer used to publish
        # those `?`s as the cache - swnames.fill was only ever wired into
        # swtable.py's own CLI, which nothing in the run path calls. Every
        # consumer of this file matches on the NAME (padglhost's key binds,
        # plunge.py's trough, switchxy's join), so a nameless list parses
        # fine and disables all of them at once, silently - beatles' guided
        # setup with dead flipper keys is what that looks like. fill never
        # overwrites a name the game itself supplied and refuses over
        # guessing, so this is safe on every branch above, the ELF walk's
        # already-named rows included.
        live_rows, fill_report = swnames.fill(live_rows, game, elf)
        for line in fill_report:
            if not line.startswith("every switch already has"):
                say("               %s" % line)
        # ★ ITEM 49: NAME a failed write instead of dying in a log nobody
        # reads. The background pass runs as the desktop user and pass one
        # (root, on a pivot run) creates this directory - before watch.sh
        # chowned it in between, the PermissionError here was an uncaught
        # traceback in padtables.log and the switch table silently never
        # existed, on this run and every run after it. build()'s own
        # docstring promises it never raises for a missing part; this was
        # the one write that could.
        try:
            _write(sw_list, swtable.text(game, live_rows))
        except OSError as exc:
            say("  switches     FAILED to write %s: %s" % (sw_list, exc))
            say("  switches     (a root-owned tables dir from an old run? a "
                "PIVOT run heals it at start; a plain run cannot chown "
                "root's files - fix by hand: sudo chown -R <you> that dir)")
            return made
        made["switch_list.txt"] = sw_list
        say("  switches     %d in the game's own table (%s)"
            % (len(live_rows), sw_src))

    # --- positions, which NO LONGER need a run (item 27) -----------------
    #
    # This join used to run off the live dump's names, inside the branch
    # above - two bugs in one place. First, a title whose switch_list was
    # cached before switch_xy existed took the (cached) early-return forever,
    # so the join never ran again and the playfield drew coils and no
    # switches (Jaws, David, 2026-08-10: "why aren't the switch locations on
    # the virtual playfield?"). Second, the LIVE names are msg_row()'s, which
    # answer `?` on every title whose message-table address resolves wrong -
    # jaws, led_zeppelin, elvira - which is precisely why swnames.py fills
    # switch_list.txt from the DEVICE table instead. So join from the on-disk
    # list swnames has already named, and no run is involved at all.
    # `repaired` forces the join: the positions are keyed on the names the
    # repair just filled in, so a switch_xy.txt from before the repair (or a
    # join the nameless list made impossible) is stale by construction.
    if (force or repaired or not os.path.exists(sw_xy)) \
            and os.path.exists(sw_list):
        if recs is None and os.path.exists(dev_dest):
            try:
                recs = devicexy.build(game)
            except (OSError, SystemExit):
                recs = None
        if recs:
            names = switchxy.read_list(sw_list)
            joined = switchxy.join(names, recs)
            if joined:
                try:
                    _write(sw_xy, switchxy.text(game, joined))
                    made["switch_xy.txt"] = sw_xy
                    say("  positions    %d switches placed on the artwork"
                        % len(joined))
                except OSError as exc:
                    say("  positions    FAILED to write %s: %s" % (sw_xy, exc))
            else:
                # Real and worth saying out loud: it means the two tables
                # share no names - a title whose device table names things
                # differently, or a list that is still all `?`.
                say("  positions    NONE of the %d named switches matched a "
                    "device-table name" % len(names))
    return made


def drawable(game=None):
    """Whether this title has enough to draw a playfield WITHOUT a run.

    The caller that matters is watch.sh, and the decision it makes with this is
    the difference between a useful first run and a useless one:

      * yes - artwork or device positions exist, so open the window NOW and
        finish the switch tables behind it. The window shows the playfield,
        its inserts and its coils immediately, and gains clickable switches on
        the next run of that title.
      * no  - there is nothing to draw at all until the game publishes its
        switch list, so waiting for it is the only way the window is worth
        opening. Led Zeppelin and Elvira are this case: no images/Test and no
        device table anywhere in the binary.
    """
    game = gameinfo.active(game)
    if not game:
        return False
    tdir = gameinfo.table_dir(game)
    if not tdir:
        return False
    art = os.path.join(tdir, "playfield.png")
    if os.path.exists(art):
        return True
    dev = os.path.join(tdir, "device_xy.txt")
    try:
        with open(dev) as f:
            return any(not ln.startswith("#") and ln.strip() for ln in f)
    except OSError:
        return False


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--game", default=None, help="title (default: the active one)")
    ap.add_argument("--log", default=None, help="a run log to read the switch table from")
    ap.add_argument("--wait", type=float, default=0,
                    help="seconds to wait for the switch dump to appear")
    ap.add_argument("--force", action="store_true", help="rebuild everything")
    a = ap.parse_args()
    made = build(a.game, a.log, a.wait, a.force)
    if not made:
        print("nothing written")
    # A machine-readable last line, so watch.sh can decide whether to open the
    # playfield window now or wait for the switch table first.
    print("drawable=%s" % ("yes" if drawable(a.game) else "no"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
