"""Online music identification via AcoustID + MusicBrainz.

The jukebox music tracks decode to ``audio/idxNNNN.wav`` named only by index;
the song title is unrecoverable from the firmware (it lives in runtime game
rule logic).  For band pins (Led Zeppelin, Rush, the Beatles, ...) the music is
a commercial master recording, so we can identify each clip the same way
MusicBrainz Picard does: build an acoustic **fingerprint** locally and look it
up in the free **AcoustID** database, which returns the MusicBrainz title +
artist.  No reference library and no manual pairing required.

The fingerprint is generated by **ffmpeg** (already a project dependency for
video) via its built-in ``chromaprint`` muxer — so there's no extra ``fpcalc``
binary to bundle.  Lookups need a free AcoustID *application* key (lookup-only,
~3 req/s); see ``client_key`` below.  Original-soundtrack pins (e.g. TMNT) won't
match — that music isn't in any database — so callers should fall back to the
``music`` isolation tag for those.
"""

import gzip
import json
import os
import re
import subprocess
import urllib.error
import urllib.parse
import urllib.request

# Reuse the shared ffmpeg layer: robust exe discovery + the Windows
# CREATE_NO_WINDOW flag so fingerprinting never flashes a console window.
from . import net
from .audio import _CREATE_FLAGS, find_ffmpeg, probe_duration
from .pipeline_base import BasePipeline, PipelineError

ACOUSTID_LOOKUP_URL = "https://api.acoustid.org/v2/lookup"
MUSIC_IDS_CSV = "music_titles.csv"

# Free AcoustID *application* key (lookup-only, ~3 req/s, no per-user signup
# needed — one shipped key covers everyone at this volume).  Registered for
# this tool at https://acoustid.org/new-application.  Override per-run via the
# ACOUSTID_API_KEY env var or ``client_key=``.
DEFAULT_CLIENT_KEY = "GpHGLK0jmy"

# Only try to identify WAVs at least this long (music, not SFX/callouts).
DEFAULT_MIN_MUSIC_SECONDS = 20.0
# AcoustID match scores run 0..1; below this we treat it as "no confident id".
DEFAULT_MIN_SCORE = 0.50

# A decode WAV that already carries a name label ("idx0384 - SE FX ZEPPELIN
# AWARD.wav", "idx0100 - Welcome to the machine.wav"), with the optional
# play-length prefix.  The bare " - music" isolation tag is the one label that
# stays a candidate — it marks exactly the clips this pipeline exists to title.
_LABELED_DECODE_RE = re.compile(
    r"^(?:\d+m\d+s\d+ - )?(?:idx\d+|music_cat\d+_\d+) - (?P<label>.+)\.wav$",
    re.IGNORECASE)


def _already_named(fn):
    """True when *fn* already has a real name and must not be fingerprinted.

    On a band pin, long SFX carry song riffs, so AcoustID happily "titles" a
    Sound-Test-named effect too — monkeybug's Led Zeppelin extract grew names
    like "idx0384 - SE FX ZEPPELIN AWARD - Immigrant Song.wav" (the game's own
    name AND the song of the riff inside it, both true but read as a
    double-label bug).  It also stops a re-run from stacking a second title
    onto an already-titled track.  Files that don't look like decode outputs
    at all are left as candidates (other plugins name their audio freely)."""
    m = _LABELED_DECODE_RE.match(fn)
    if not m:
        return False
    return m.group("label").strip().lower() != "music"

NO_KEY_HINT = (
    "Online music ID needs a free AcoustID application key.\n\n"
    "Get one (lookup-only, ~30 s) at:\n"
    "  https://acoustid.org/new-application\n\n"
    "Then set ACOUSTID_API_KEY in the environment, or paste it into the\n"
    "music-ID settings.")

FFMPEG_HINT = (
    "Online music ID needs `ffmpeg` (already used for video) to compute the\n"
    "acoustic fingerprint.  Install ffmpeg and ensure it's on PATH.")


def resolve_client_key(explicit=None):
    """Pick the AcoustID key: explicit arg > env var > bundled default."""
    return (explicit or os.environ.get("ACOUSTID_API_KEY")
            or DEFAULT_CLIENT_KEY or "").strip()


# ---------------------------------------------------------------------------
# Fingerprinting (ffmpeg) + lookup (AcoustID)
# ---------------------------------------------------------------------------
def fingerprint_file(path):
    """Return ``(fingerprint_b64, duration_seconds_int)`` via ffmpeg's
    chromaprint muxer.  Raises ValueError on a decode/fingerprint failure.

    Runs fully headless: ``creationflags=_CREATE_FLAGS`` keeps Windows from
    flashing a console window per clip."""
    ffmpeg = find_ffmpeg()
    if not ffmpeg:
        raise PipelineError("Identify music", FFMPEG_HINT)
    proc = subprocess.run(
        [ffmpeg, "-hide_banner", "-v", "error", "-i", path,
         "-f", "chromaprint", "-fp_format", "base64", "-"],
        capture_output=True, creationflags=_CREATE_FLAGS)
    fp = proc.stdout.decode("ascii", "ignore").strip()
    if proc.returncode != 0 or not fp:
        msg = proc.stderr.decode("utf-8", "replace")[:300]
        raise ValueError("ffmpeg fingerprint failed for %s: %s"
                         % (os.path.basename(path), msg))
    return fp, int(round(probe_duration(path)))


def lookup(fingerprint, duration, client_key, timeout=20,
           _opener=net.urlopen):
    """Query AcoustID; return the parsed JSON dict.  ``_opener`` is injectable
    for tests.  Raises ValueError on a transport/HTTP error."""
    fields = [
        ("client", client_key),
        ("duration", str(int(duration))),
        # ``sources`` = how many people submitted each recording's fingerprint;
        # it's our canonicity tiebreaker when one acoustic match maps to several
        # MusicBrainz recordings (the album master has thousands, a mistag has 1).
        # Space-separated; urlencode form-encodes the space to '+', which is the
        # separator AcoustID expects (encoding the '+' literally breaks it).
        ("meta", "recordings sources"),
        ("fingerprint", fingerprint),
    ]
    body = urllib.parse.urlencode(fields)
    body = gzip.compress(body.encode("ascii"))   # fingerprints are long
    req = urllib.request.Request(
        ACOUSTID_LOOKUP_URL, data=body,
        headers={"Content-Type": "application/x-www-form-urlencoded",
                 "Content-Encoding": "gzip",
                 "User-Agent": "PinballAssetDecryptor/1.0"})
    try:
        with _opener(req, timeout=timeout) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.URLError as e:
        raise ValueError("AcoustID request failed: %s" % e)


def recording_candidates(acoustid_json, min_score=0.0):
    """Flatten an AcoustID response to ``(title, artist, score, sources)``
    rows for every recording whose result score >= *min_score*."""
    out = []
    if not isinstance(acoustid_json, dict) \
            or acoustid_json.get("status") != "ok":
        return out
    for result in acoustid_json.get("results", []):
        score = float(result.get("score", 0.0) or 0.0)
        if score < min_score:
            continue
        for rec in result.get("recordings", []) or []:
            title = (rec.get("title") or "").strip()
            if not title:
                continue
            artist = ", ".join(
                a.get("name", "")
                for a in rec.get("artists", []) or []).strip()
            sources = int(rec.get("sources", 0) or 0)
            out.append((title, artist, score, sources))
    return out


def _norm_artist(s):
    return "".join(c for c in (s or "").lower() if c.isalnum())


def pick_best(cands, prefer_artist=None):
    """Choose ``(title, artist, score)`` from candidate rows, preferring the
    machine's artist, then match score, then source count (canonicity).  One
    acoustic match often maps to several MusicBrainz recordings (the album
    master + samples/mistags); preferring the pin's own artist and the
    most-sourced recording resolves it (e.g. Led Zeppelin over a 1-source
    'Metro Station - Disco' for Immigrant Song)."""
    if not cands:
        return None, None, 0.0
    pa = _norm_artist(prefer_artist) if prefer_artist else None

    def key(c):
        title, artist, score, sources = c
        a_match = 1 if (pa and pa in _norm_artist(artist)) else 0
        return (a_match, round(score, 2), sources)

    title, artist, score, _src = max(cands, key=key)
    return title, artist or None, score


def dominant_artist(all_cands):
    """The artist with the most total sources across every track's
    candidates — i.e. the band this jukebox belongs to."""
    tally = {}
    for title, artist, score, sources in all_cands:
        if artist:
            tally[artist] = tally.get(artist, 0) + sources
    return max(tally, key=tally.get) if tally else None


def best_match(acoustid_json, prefer_artist=None, min_score=0.0):
    """Convenience single-response matcher (no corpus context)."""
    return pick_best(recording_candidates(acoustid_json, min_score),
                     prefer_artist)


# ---------------------------------------------------------------------------
# Pipeline
# ---------------------------------------------------------------------------
_FORBIDDEN = '<>:"|?*/\\'


def _sanitize(s, maxlen=80):
    s = "".join(("_" if c in _FORBIDDEN else c) for c in s).strip()
    s = " ".join(s.split())
    return s[:maxlen].rstrip(". ") or "match"


class MusicIdPipeline(BasePipeline):
    """Identify each extracted music WAV online via AcoustID + MusicBrainz.

    Phase 0: scan assets for music-candidate WAVs.
    Phase 1: fingerprint + look up each clip.
    Phase 2: write music_titles.csv (+ optional rename of confident matches).
    """

    phases = ("Scan", "Identify", "Write CSV")

    def __init__(self, assets_dir, log_cb, phase_cb, progress_cb, done_cb,
                 client_key=None, min_music_seconds=DEFAULT_MIN_MUSIC_SECONDS,
                 min_score=DEFAULT_MIN_SCORE, rename_after=False,
                 expected_artist=None):
        super().__init__(log_cb, phase_cb, progress_cb, done_cb)
        self.assets_dir = assets_dir
        self.client_key = resolve_client_key(client_key)
        self.min_music_seconds = float(min_music_seconds)
        self.min_score = float(min_score)
        self.rename_after = rename_after
        # The pin's band, if known by the caller; else auto-detected as the
        # artist that dominates the jukebox corpus.
        self.expected_artist = expected_artist

    def _wav_seconds(self, path):
        import wave
        try:
            w = wave.open(path, "rb")
            try:
                return w.getnframes() / float(w.getframerate() or 1)
            finally:
                w.close()
        except (wave.Error, EOFError, OSError):
            return 0.0

    def _run(self):
        self._set_phase(0)
        if not self.client_key:
            raise PipelineError("Identify music", NO_KEY_HINT)
        if not os.path.isdir(self.assets_dir):
            raise PipelineError("Identify music",
                "Assets folder not found: %s" % self.assets_dir)
        music = []
        skipped_named = 0
        for dp, _dn, fns in os.walk(self.assets_dir):
            for fn in fns:
                if fn.lower().endswith(".wav") and not fn.startswith("."):
                    if _already_named(fn):
                        skipped_named += 1
                        continue
                    p = os.path.join(dp, fn)
                    if self._wav_seconds(p) >= self.min_music_seconds:
                        music.append(p)
        music.sort()
        if skipped_named:
            self._log("  Skipping %d already-named file(s) — Sound-Test "
                      "SFX and call-outs keep their names." % skipped_named,
                      "info")
        if not music:
            raise PipelineError("Identify music",
                "No WAV >= %.0fs found under %s.\nRun Extract first, or lower "
                "the music-length threshold." % (self.min_music_seconds,
                                                 self.assets_dir))
        self._log("Identifying %d music clip(s) via AcoustID..."
                  % len(music), "info")

        # Pass 1: fingerprint + look up each clip, collecting candidate
        # recordings (we resolve titles only after we know the pin's band).
        self._set_phase(1)
        per_clip = []   # (rel, candidates)
        all_cands = []  # flattened, for dominant-artist detection
        for i, wp in enumerate(music):
            self._check_cancel()
            rel = os.path.relpath(wp, self.assets_dir).replace("\\", "/")
            try:
                fp, dur = fingerprint_file(wp)
                data = lookup(fp, dur, self.client_key)
                cands = recording_candidates(data, self.min_score)
            except (ValueError, PipelineError) as e:
                self._log("  %s: %s" % (rel, e), "warning")
                cands = []
            per_clip.append((rel, cands))
            all_cands.extend(cands)
            self._progress(i + 1, len(music), "identifying")

        # The pin's band = the caller's hint, else the artist dominating the
        # jukebox corpus.  Preferring it picks the right recording when one
        # fingerprint maps to several (the band's track vs an unrelated sampler).
        band = self.expected_artist or dominant_artist(all_cands)
        if band:
            self._log("  Preferring artist: %s" % band, "info")

        rows = []  # (rel, title, artist, score)
        for rel, cands in per_clip:
            title, artist, score = pick_best(cands, band)
            rows.append((rel, title or "", artist or "", score))
            if title and score >= self.min_score:
                self._log("  [OK] %s -> %s%s (%.2f)"
                          % (rel, title, " - " + artist if artist else "",
                             score), "info")
            else:
                self._log("  [no id] %s (%s)" % (
                    rel, "%.2f" % score if title else "no match"), "info")

        self._set_phase(2)
        renamed = self._rename(rows) if self.rename_after else 0
        out = os.path.join(self.assets_dir, MUSIC_IDS_CSV)
        import csv
        with open(out, "w", encoding="utf-8", newline="") as f:
            w = csv.writer(f)
            w.writerow(["relative_path", "title", "artist", "score"])
            for rel, t, a, s in rows:
                w.writerow([rel, t, a, "%.3f" % s])
        conf = sum(1 for r in rows if r[1] and r[3] >= self.min_score)
        extra = ("\nRenamed %d confident match(es)." % renamed
                 if self.rename_after else "")
        self._log("Done.", "success")
        # A low hit-rate is normal for some titles and is NOT a failure:
        # AcoustID does exact-recording matching, so it only IDs a clip when the
        # pin plays the same master that's been fingerprinted in its database.
        # Pins that use re-masters / re-mixes / game-edited cuts (or original
        # soundtracks not in any database) just won't match, even for famous
        # songs — the audio still extracted fine; only the auto-naming is
        # limited.  Matches per title therefore vary a lot (a band pin using the
        # commercial remasters can hit most tracks; another can hit only a few).
        low = conf < max(1, len(rows) // 2)
        note = (
            "A low match count is expected for some pins and does NOT mean "
            "extraction failed — the audio is fine, only the auto-naming is "
            "limited.\nAcoustID matches the exact commercial recording; pins "
            "that use non-standard masters / re-mixes / game-edited cuts (or "
            "original soundtracks) won't match even well-known songs. Unmatched "
            "clips keep their 'music' tag; you can name those by ear (e.g. "
            "Shazam)."
            if low else
            "No match usually means a non-standard master / game-edited cut or "
            "an original-soundtrack track not in any fingerprint database.")
        self._done(True,
            "Identified %d of %d music clip(s) (score >= %.2f).%s\n\n"
            "Output: %s\n\n%s"
            % (conf, len(rows), self.min_score, extra, out, note))

    def _rename(self, rows):
        n = 0
        renames = {}            # old_rel -> new_rel, to re-point the baseline
        for k, (rel, title, artist, score) in enumerate(rows):
            if not title or score < self.min_score:
                continue
            src = os.path.join(self.assets_dir, rel)
            d, base = os.path.split(rel)
            stem, ext = os.path.splitext(base)
            label = "%s - %s" % (artist, title) if artist else title
            new_base = "%s - %s%s" % (stem, _sanitize(label), ext)
            new_rel = os.path.join(d, new_base) if d else new_base
            dst = os.path.join(self.assets_dir, new_rel)
            if os.path.abspath(dst) == os.path.abspath(src):
                continue
            if os.path.exists(dst):
                self._log("  skip rename %s: target exists" % rel, "info")
                continue
            try:
                os.replace(src, dst)
                new_rel_fs = new_rel.replace("\\", "/")
                rows[k] = (new_rel_fs, title, artist, score)
                renames[rel.replace("\\", "/")] = new_rel_fs
                n += 1
            except OSError as e:
                self._log("  rename failed %s: %s" % (rel, e), "error")
        # The rename moves the WAV after Extract wrote .checksums.md5, so
        # re-point the baseline to the new names (bytes unchanged) — else the
        # Replace-Audio tab flags every auto-named track as "changed on disk".
        if renames:
            from .checksums import rename_in_baseline
            rename_in_baseline(self.assets_dir, renames)
        return n
