#!/usr/bin/env python3
"""gen_themes.py themes.json theme_table.h - the boot menu's colour themes as a C header.

themes.json is the ONE definition of the themes (codeselect, mkmulticard.py and the app's
Multi-boot tab all read it); this turns it into the enum, the role names and the colour table
the selector compiles in.  Run by the Makefile into $(BUILD); never edit the output.

The file is checked here rather than trusted: distinct roles named [a-z_]+, every theme naming
every role with an RRGGBB value, names [a-z][a-z0-9_]* of at most 31 characters, 'custom'
reserved (it is the default theme plus a conf's overrides), and a default that exists.  A bad
file fails the BUILD, not the machine."""
import json
import re
import sys

NAME_RE = re.compile(r"^[a-z][a-z0-9_]{0,30}$")
ROLE_RE = re.compile(r"^[a-z][a-z_]*$")
HEX_RE = re.compile(r"^[0-9a-fA-F]{6}$")


def load(path):
    """-> (roles, themes, default), checked; SystemExit with the reason otherwise."""
    with open(path, "r", encoding="utf-8") as f:
        doc = json.load(f)
    roles = doc.get("roles")
    themes = doc.get("themes")
    default = doc.get("default")
    if not isinstance(roles, list) or not roles or len(set(roles)) != len(roles):
        raise SystemExit("%s: 'roles' must be a non-empty list of distinct names" % path)
    for r in roles:
        if not isinstance(r, str) or not ROLE_RE.match(r):
            raise SystemExit("%s: role %r is not [a-z_]+" % (path, r))
    if not isinstance(themes, list) or not themes:
        raise SystemExit("%s: 'themes' must be a non-empty list" % path)
    names = []
    for t in themes:
        name = t.get("name")
        if not isinstance(name, str) or not NAME_RE.match(name) or name == "custom":
            raise SystemExit("%s: theme name %r must be [a-z][a-z0-9_]* (at most 31 characters) "
                             "and not 'custom'" % (path, name))
        if name in names:
            raise SystemExit("%s: theme %r is listed twice" % (path, name))
        names.append(name)
        colors = t.get("colors") or {}
        missing = [r for r in roles if r not in colors]
        extra = [r for r in colors if r not in roles]
        if missing or extra:
            raise SystemExit("%s: theme %r: missing %r, unknown %r" % (path, name, missing, extra))
        for r in roles:
            if not isinstance(colors[r], str) or not HEX_RE.match(colors[r]):
                raise SystemExit("%s: theme %r: %s=%r is not RRGGBB" % (path, name, r, colors[r]))
    if default not in names:
        raise SystemExit("%s: default %r is not one of the themes" % (path, default))
    return roles, themes, default


def render(roles, themes, default):
    """The header text."""
    out = ["/* generated by gen_themes.py from themes.json - do not edit; edit the JSON */",
           "#ifndef CODESELECT_THEME_TABLE_H",
           "#define CODESELECT_THEME_TABLE_H",
           "#define TH_N %d" % len(roles),
           "enum theme_role {"]
    out += ["    TH_%s%s" % (r.upper(), "," if i < len(roles) - 1 else "")
            for i, r in enumerate(roles)]
    out += ["};",
            "#define THEME_DEFAULT \"%s\"" % default,
            "#define THEME_COUNT %d" % len(themes),
            "#endif",
            "",
            "/* the data, once, in theme.c (after struct theme is declared) */",
            "#ifdef THEME_DEFINE_TABLE",
            "static const char *const theme_role_names[TH_N] = {"]
    out += ["    \"%s\"%s" % (r, "," if i < len(roles) - 1 else "") for i, r in enumerate(roles)]
    out += ["};", "static const struct theme theme_table[THEME_COUNT] = {"]
    for i, t in enumerate(themes):
        vals = ", ".join("0x%s" % t["colors"][r].lower() for r in roles)
        out.append("    { \"%s\", { %s } }%s" % (t["name"], vals, "," if i < len(themes) - 1 else ""))
    out += ["};", "#endif", ""]
    return "\n".join(out)


def main(argv):
    if len(argv) != 3:
        raise SystemExit("usage: gen_themes.py themes.json theme_table.h")
    roles, themes, default = load(argv[1])
    text = render(roles, themes, default)
    if argv[2] == "-":
        sys.stdout.write(text)
    else:
        with open(argv[2], "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
