/* pad_mode_assets.h - a CODE mode's OWN clip, screen, music and calls, as the app's Write put them
 * on the card (MODE_SDK.md, "A code mode's own assets").
 *
 * A mode made in the Modes tab's form gets its sounds and clips through its mode FILE, which
 * mode_file.c reads. A mode written in C has no mode file, so the build (the app's Write, and Try
 * it, which is Write's own code) puts ONE small file beside mode.so for it, named after the mode's
 * folder in the card project (modes/<folder>/<folder>.c):
 *
 *     /usr/local/padmode/<folder>.assets     on a card
 *     /dump/<folder>.assets                  in the emulator
 *
 *     # GENERATED by the app's Write from modes/<folder>/assets.json
 *     name   KING GHIDORAH
 *     screen PadMode_<folder>_Screen PadMode_<folder>_Screen.PadMode_<folder>_Screen_Words
 *     clip   start PadMode_<folder>_Clip          a clip the build added to the game's video bank
 *     music  125 618                              the music carrier, and this mode's own bed (a sid)
 *     call   sever 1251 1850 4                    a call of its own: cue, carrier request, its own
 *     call   spike 1249 700 3                     length in ms, and its priority on the voice bus
 *
 * The mode names its CUES itself ("sever", "won", "lost" ...) and the project's assets.json maps
 * each cue to a WAV; the build chooses the carriers and writes this file. So the same mode.so plays
 * whatever the build carried, and a cue the build did not carry is simply not there:
 *
 *     static struct pa_assets own = { .folder = "ghidorah_heads" };
 *     on_init:   pa_load(&own);
 *     on_tick:   pa_tick(&own);                    EVERY tick, running or not (an end call outlives
 *                                                  the mode, and the game's music comes back after)
 *     start:     pa_start(&own);                   its music (the game's fades out first) and its
 *                                                  start clip (half a second later, from the tick)
 *     an event:  pa_call(&own, "sever");
 *     time up:   if (!pa_call(&own, "lost")) pm_callout(pm_callout_id("time_up"));
 *     end:       pa_end(&own);                     its music fades (400 ms), the game's comes back
 *
 * WHAT IT DOES WITH THE SOUND (the same rules mode_file.c follows for a tab mode, item 150 and its
 * follow-up; MODE_SDK.md "Sounds of your own"): a call takes the voice bus at its priority (4, or 3
 * for a call that repeats) WITHOUT the steal flag, so it is never cut mid-sound; the game's lower
 * speech on the voice bus is faded (60 ms) before it plays, and so is a call of this mode's own that
 * still sounds (30 ms: the newest event speaks); a call played again while its previous play still
 * sounds starts over (the engine would not restart it); a call the game's speech refuses waits up to
 * 1.5 s (0.8 s at priority 3) and is then dropped with a log line naming that speech; a call whose
 * own sound is over is faded (40 ms), never cut; a priority-3 call whose previous play still sounds
 * is skipped. The
 * music: the game's music fades out (250 ms), the carrier is pointed at this mode's bed and played,
 * started again if it stops, any music of the game's that starts under it is faded; at the end it
 * fades (400 ms), the carrier's own list is put back and the game's music that was playing at the
 * start plays again.
 *
 * Everything here is `static` (a mode copied out of the SDK takes the header with it), and the
 * music's state is one WEAK definition shared by every mode in the object, so one mode's music
 * ending and the next one's starting never fight over the carrier. Nothing here runs from a
 * constructor and nothing blocks (MODE_SDK.md "The rules").
 */
#ifndef PAD_MODE_ASSETS_H
#define PAD_MODE_ASSETS_H

#include "pad_mode.h"

#define PA_CALLS_MAX        16
#define PA_CUE              16          /* a cue's name, with its 0 */
#define PA_NAME             64
#define PA_WAITING_MAX      6
#define PA_STOPS_MAX        8
#define PA_BUS_MUSIC        0x01u       /* the channel bus bits measured on Godzilla (item 150) */
#define PA_BUS_VOICE        0x02u
#define PA_CLIP_AFTER_MS    500         /* MODE_SDK.md "Clips race the game's own" */
#define PA_MUSIC_WAIT_MS    260         /* the game's music fades 250 ms before ours starts */
#define PA_MUSIC_FADE_MS    400
#define PA_POLL_MS          500
#define PA_FILE_MAX         2048

#define PA_UNUSED __attribute__((unused))

struct pa_call { char cue[PA_CUE]; unsigned request, ms, prio; };

struct pa_assets {
    const char *folder;                   /* the mode's folder name: its file is <folder>.assets */
    int loaded, looked;                   /* found and read; looked for at least once */
    char name[PA_NAME];
    char clip_start[PA_NAME];             /* "" = no clip of its own */
    unsigned music, music_sid;            /* 0 = no music of its own */
    struct pa_call calls[PA_CALLS_MAX];
    unsigned n_calls;
    /* what is under way */
    int running;                          /* between pa_start and pa_end */
    unsigned long clip_due;               /* pm_ms() the start clip plays at; 0 = none */
    unsigned long shot_until[PA_CALLS_MAX];   /* a priority-3 call still sounds until then */
    struct { unsigned request, prio, ms, holder; unsigned long due, deadline; const char *cue; } waiting[PA_WAITING_MAX];
    struct { unsigned request; unsigned long due; } stops[PA_STOPS_MAX];
    unsigned long next_poll;
    unsigned music_restarts;
};

/* ONE music state for every mode in the object (weak: the linker keeps one). */
struct pa_music_state {
    unsigned request, sid;                /* ours, while a mode's music runs */
    const char *owner;                    /* the folder whose music it is */
    unsigned long start_due;              /* ours starts then (the game's is fading); 0 = started */
    unsigned game;                        /* the game's music at the start, played again at the end */
    unsigned after_request, after_game;   /* after an end: once ours has faded, */
    unsigned long after_due;              /*   put the carrier's list back and the game's music on */
    unsigned silenced[4];                 /* the game's music faded under ours (each logged once) */
    const char *after_owner;              /* whose music that was (for the log: any mode's tick runs it) */
    unsigned bus1[4];                     /* what held the music bus at the last look (logged on a change) */
    int nbus1;
    unsigned long check_due;              /* after the end: look at the music bus once, then */
};
__attribute__((weak, visibility("hidden"))) struct pa_music_state pa_music;

/* ---- the file ----------------------------------------------------------------------------------- */
static PA_UNUSED int pa_space(char c) { return c == ' ' || c == '\t' || c == '\r'; }

/* the next word of *s into out (at most cap-1 chars); 1 if there was one */
static PA_UNUSED int pa_word(const char **s, char *out, unsigned cap)
{
    const char *p = *s;
    unsigned n = 0;
    while (*p && pa_space(*p)) p++;
    if (!*p || *p == '\n') { *s = p; if (cap) out[0] = 0; return 0; }
    while (*p && *p != '\n' && !pa_space(*p)) {
        if (n + 1 < cap) out[n++] = *p;
        p++;
    }
    out[n] = 0;
    *s = p;
    return 1;
}

static PA_UNUSED unsigned pa_num(const char *w)
{
    unsigned v = 0;
    while (*w >= '0' && *w <= '9') v = v * 10u + (unsigned)(*w++ - '0');
    return v;
}

static PA_UNUSED int pa_is(const char *a, const char *b)
{
    while (*a && *a == *b) { a++; b++; }
    return *a == *b;
}

/* the rest of the line after the key, trimmed */
static PA_UNUSED void pa_rest(const char *s, char *out, unsigned cap)
{
    unsigned n = 0;
    while (*s && pa_space(*s)) s++;
    while (*s && *s != '\n' && n + 1 < cap) out[n++] = *s++;
    while (n && pa_space(out[n - 1])) n--;
    out[n] = 0;
}

static PA_UNUSED void pa_parse_line(struct pa_assets *a, const char *s)
{
    char key[16], w[PA_NAME];
    if (!pa_word(&s, key, sizeof key) || key[0] == '#') return;
    if (pa_is(key, "name")) {
        pa_rest(s, a->name, sizeof a->name);
    } else if (pa_is(key, "clip")) {
        pa_word(&s, w, sizeof w);                                    /* when: start */
        if (pa_is(w, "start")) pa_word(&s, a->clip_start, sizeof a->clip_start);
    } else if (pa_is(key, "music")) {
        if (pa_word(&s, w, sizeof w)) a->music = pa_num(w);
        if (pa_word(&s, w, sizeof w)) a->music_sid = pa_num(w);
    } else if (pa_is(key, "call") && a->n_calls < PA_CALLS_MAX) {
        struct pa_call *c = &a->calls[a->n_calls];
        if (!pa_word(&s, c->cue, sizeof c->cue)) return;
        if (!pa_word(&s, w, sizeof w) || !(c->request = pa_num(w))) return;
        c->ms = pa_word(&s, w, sizeof w) ? pa_num(w) : 0;
        c->prio = pa_word(&s, w, sizeof w) ? pa_num(w) : 4;
        if (c->prio < 1 || c->prio > 7) c->prio = 4;
        a->n_calls++;
    }
    /* screen and anything newer: the mode finds its screen by name (intricate_kit.h) */
}

/* Read <folder>.assets from the card's padmode directory, then the rig's /dump. Once found it is
 * not read again; until then every call looks (pa_start looks again, so a file put in the guest
 * after boot is still found). 1 = the mode has its file. */
static PA_UNUSED int pa_load(struct pa_assets *a)
{
    static const char *const dirs[2] = { "/usr/local/padmode/", "/dump/" };
    char path[128], buf[PA_FILE_MAX];
    long n = -1;
    unsigned d, i;
    const char *line;
    if (a->loaded || !a->folder) return a->loaded;
    for (d = 0; d < 2 && n < 0; d++) {
        pm_snprintf(path, sizeof path, "%s%s.assets", dirs[d], a->folder);
        n = pm_read_file(path, buf, sizeof buf - 1);
    }
    if (n < 0) {
        if (!a->looked) pm_log("own assets: no %s.assets - the mode plays the game's own sounds only", a->folder);
        a->looked = 1;
        return 0;
    }
    buf[n] = 0;
    a->looked = a->loaded = 1;
    a->n_calls = 0;
    a->music = a->music_sid = 0;
    a->clip_start[0] = 0;
    for (line = buf; *line; ) {
        pa_parse_line(a, line);
        while (*line && *line != '\n') line++;
        if (*line) line++;
    }
    pm_log("own assets: %s (%s): %u call(s)%s%s%s", path, a->name[0] ? a->name : a->folder, a->n_calls,
           a->music ? ", its own music" : "", a->music_sid ? " on its own bed" : "",
           a->clip_start[0] ? ", a start clip" : "");
    for (i = 0; i < a->n_calls; i++)
        pm_log("own assets:   call %-10s request %u, %u ms, priority %u", a->calls[i].cue, a->calls[i].request,
               a->calls[i].ms, a->calls[i].prio);
    return 1;
}

static PA_UNUSED int pa_find(const struct pa_assets *a, const char *cue)
{
    unsigned i;
    for (i = 0; i < a->n_calls; i++)
        if (pa_is(a->calls[i].cue, cue)) return (int)i;
    return -1;
}

/* 1 if the build carried a call for this cue */
static PA_UNUSED int pa_has(struct pa_assets *a, const char *cue)
{
    pa_load(a);
    return pa_find(a, cue) >= 0;
}

/* ---- calls -------------------------------------------------------------------------------------- */
static PA_UNUSED int pa_request_prio(unsigned request)
{
    int pair = pm_sound_priority(request, -1, -1);
    return pair < 0 ? -1 : pair >> 8;
}

/* stop <request> once its own <ms> have played (faded, never cut); a new play moves the time */
static PA_UNUSED void pa_stop_after(struct pa_assets *a, unsigned request, unsigned ms)
{
    unsigned long due;
    int i, free_i = -1;
    if (!request || !ms) return;
    due = pm_ms() + ms + ms / 8 + 120;
    for (i = 0; i < PA_STOPS_MAX; i++) {
        if (a->stops[i].request == request) { a->stops[i].due = due; return; }
        if (!a->stops[i].request && free_i < 0) free_i = i;
    }
    if (free_i >= 0) { a->stops[free_i].request = request; a->stops[free_i].due = due; }
}

/* 1 if <request> is one of this mode's own calls */
static PA_UNUSED int pa_own(const struct pa_assets *a, unsigned request)
{
    unsigned i;
    for (i = 0; i < a->n_calls; i++)
        if (a->calls[i].request == request) return 1;
    return 0;
}

/* 1 = played now; 0 = not yet: something on the voice bus is being faded first, or the bus is held
 * by the game's speech this call cannot take (*holder names it). What is faded: the game's LOWER
 * speech (60 ms); a call of this mode's OWN (30 ms: the newest event speaks); this call's own
 * previous play (30 ms: a call played again starts over - the engine does not restart a request that
 * still sounds). `say` logs what is faded (the first try; a retry is quiet). */
static PA_UNUSED int pa_try(struct pa_assets *a, unsigned request, unsigned prio, const char *cue, int say,
                            unsigned *holder)
{
    unsigned reqs[8], buses[8];
    int n = pm_sound_playing(reqs, buses, 8), i, faded = 0;
    if (holder) *holder = 0;
    for (i = 0; i < n && i < 8; i++) {
        int p;
        if (!(buses[i] & PA_BUS_VOICE)) continue;
        if (reqs[i] == request) {
            pm_sound_fade(request, 30);
            if (say) pm_log("own sound: call %s (%u) starts over - its previous play is faded out first", cue, request);
            faded = 1;
            continue;
        }
        if (pa_own(a, reqs[i])) {
            pm_sound_fade(reqs[i], 30);
            if (say) pm_log("own sound: call %s (%u) waits 70 ms - this mode's own call %u is faded out first "
                            "(the newest event speaks)", cue, request, reqs[i]);
            faded = 1;
            continue;
        }
        p = pa_request_prio(reqs[i]);
        if (p < 0 || p >= (int)prio) {                    /* the game's, not ours to take (or unknown): wait */
            if (holder) *holder = reqs[i];
            return 0;
        }
        pm_sound_fade(reqs[i], 60);
        if (say) pm_log("own sound: call %s (%u) waits 70 ms - %u (priority %d) on the voice bus is faded out first",
                        cue, request, reqs[i], p);
        faded = 1;
    }
    if (faded) return 0;
    return pm_sound(request);
}

/* Play the mode's own call for `cue`. 1 = the mode has one (played now, or waiting for the voice
 * bus); 0 = the build carried none, so the caller can play the game's own callout instead. */
static PA_UNUSED int pa_call(struct pa_assets *a, const char *cue)
{
    int k, i, free_i = -1;
    unsigned holder = 0;
    struct pa_call *c;
    pa_load(a);
    k = pa_find(a, cue);
    if (k < 0) return 0;
    c = &a->calls[k];
    if (c->prio <= 3 && c->ms && pm_ms() < a->shot_until[k]) {
        pm_log("own sound: call %s (%u) skipped - its previous play still sounds", cue, c->request);
        return 1;
    }
    a->shot_until[k] = pm_ms() + c->ms;
    if (pa_try(a, c->request, c->prio, cue, 1, &holder)) {
        pm_log("own sound: call %s (%u) played", cue, c->request);
        pa_stop_after(a, c->request, c->ms);
        return 1;
    }
    for (i = 0; i < PA_WAITING_MAX; i++) {
        if (a->waiting[i].request == c->request) { free_i = i; break; }
        if (!a->waiting[i].request && free_i < 0) free_i = i;
    }
    if (free_i < 0) {
        pm_log("own sound: call %s (%u) NOT played (too many calls waiting)", cue, c->request);
        return 1;
    }
    a->waiting[free_i].request = c->request;
    a->waiting[free_i].prio = c->prio;
    a->waiting[free_i].ms = c->ms;
    a->waiting[free_i].cue = c->cue;
    a->waiting[free_i].holder = holder;
    a->waiting[free_i].due = pm_ms() + 70;
    a->waiting[free_i].deadline = pm_ms() + (c->prio <= 3 ? 800u : 1500u);
    return 1;
}

/* ---- the priorities: set at every start (MODE_SDK.md "Buses and priority") ------------------------ */
static PA_UNUSED void pa_priorities(struct pa_assets *a)
{
    unsigned i;
    int old;
    for (i = 0; i < a->n_calls; i++) {
        old = pm_sound_priority(a->calls[i].request, (int)a->calls[i].prio, 0);
        if (old < 0) {
            pm_log("own sound: call %u keeps its priority (no request table in the port)", a->calls[i].request);
            break;
        }
    }
    if (a->music) {
        old = pm_sound_priority(a->music, -1, 0);
        if (old >= 0 && (old & 1))
            pm_log("own sound: music %u holds its bus (priority %d, steal flag cleared)", a->music, old >> 8);
    }
}

/* ---- the music ---------------------------------------------------------------------------------- */
static PA_UNUSED void pa_music_start_now(void)
{
    pa_music.start_due = 0;
    pm_log("own sound: music %u%s %s", pa_music.request, pa_music.sid ? " (its own bed)" : "",
           pm_sound(pa_music.request) ? "started" : "NOT started (no sound_play in the port)");
}

static PA_UNUSED void pa_music_begin(struct pa_assets *a)
{
    unsigned reqs[8], buses[8], carry;
    int n, i;
    if (!a->music) return;
    carry = pa_music.after_game;          /* the last mode's music still fading: the game's music */
    pa_music.after_request = pa_music.after_game = 0;
    pa_music.request = a->music;
    pa_music.sid = a->music_sid;
    pa_music.owner = a->folder;
    pa_music.game = 0;
    for (i = 0; i < 4; i++) pa_music.silenced[i] = 0;
    a->music_restarts = 0;
    if (a->music_sid)
        pm_log("own sound: music %u plays its own bed, sound id %u%s", a->music, a->music_sid,
               pm_sound_sid(a->music, a->music_sid) ? "" :
               " - NOT pointed (no request table in the port), the carrier's own record plays");
    n = pm_sound_playing(reqs, buses, 8);
    for (i = 0; i < n && i < 8; i++)
        if ((buses[i] & PA_BUS_MUSIC) && reqs[i] != a->music) {
            pa_music.game = reqs[i];
            break;
        }
    if (pa_music.game) {
        pm_sound_fade(pa_music.game, 250);
        pa_music.start_due = pm_ms() + PA_MUSIC_WAIT_MS;
        pm_log("own sound: the game's music %u fades out (250 ms) before music %u starts", pa_music.game, a->music);
    } else {
        pa_music.game = carry;
        pa_music_start_now();
    }
}

/* Say what holds the MUSIC bus whenever that changes (the evidence that the mode's music is the only
 * music; once more a second after the end, when the game's music should be back). */
static PA_UNUSED void pa_music_bus_note(const unsigned *reqs, const unsigned *buses, int n, const char *when)
{
    unsigned now[4];
    int m = 0, i, same;
    char words[64];
    unsigned k = 0;
    for (i = 0; i < n && i < 8 && m < 4; i++)
        if (buses[i] & PA_BUS_MUSIC) now[m++] = reqs[i];
    same = (m == pa_music.nbus1);
    for (i = 0; same && i < m; i++) same = (now[i] == pa_music.bus1[i]);
    if (same && !when) return;
    for (i = 0; i < m; i++) pa_music.bus1[i] = now[i];
    pa_music.nbus1 = m;
    words[0] = 0;
    for (i = 0; i < m && k + 12 < sizeof words; i++)
        k += (unsigned)pm_snprintf(words + k, sizeof words - k, "%s%u", i ? " " : "", now[i]);
    pm_log("own sound: the music bus %s: %s", when ? when : "now holds", m ? words : "nothing");
}

static PA_UNUSED void pa_music_under(struct pa_assets *a)
{
    unsigned reqs[8], buses[8];
    int n, i, k;
    if (!a->music || pa_music.request != a->music || pa_music.owner != a->folder) return;
    if (pa_music.start_due) {
        if (pm_ms() >= pa_music.start_due) pa_music_start_now();
        return;
    }
    if (pm_ms() < a->next_poll) return;
    a->next_poll = pm_ms() + PA_POLL_MS;
    /* the mode's music is the only music: any of the game's (priority 1) under it is faded */
    n = pm_sound_playing(reqs, buses, 8);
    if (n >= 0) pa_music_bus_note(reqs, buses, n, 0);
    for (i = 0; i < n && i < 8; i++) {
        if (reqs[i] == a->music || pa_request_prio(reqs[i]) != 1) continue;
        pm_sound_fade(reqs[i], 250);
        for (k = 0; k < 4 && pa_music.silenced[k] && pa_music.silenced[k] != reqs[i]; k++) ;
        if (k < 4 && !pa_music.silenced[k]) {
            pa_music.silenced[k] = reqs[i];
            pm_log("own sound: the game's music %u (bus %02x) faded out under music %u", reqs[i], buses[i], a->music);
        }
    }
    if (pm_sound_active(a->music)) return;
    if (pm_sound(a->music) && (++a->music_restarts <= 3 || a->music_restarts % 20 == 0))
        pm_log("own sound: music %u had stopped - started again (%u)", a->music, a->music_restarts);
}

static PA_UNUSED void pa_music_finish(struct pa_assets *a)
{
    int playing;
    if (!a->music || pa_music.request != a->music || pa_music.owner != a->folder) return;
    if (pa_music.start_due) {             /* ended before ours even started */
        pa_music.start_due = 0;
        playing = 0;
    } else {
        playing = pm_sound_fade(a->music, PA_MUSIC_FADE_MS);
    }
    pm_log("own sound: music %u fades out at the end (%s, %u restart(s))", a->music,
           playing ? "was playing" : "was not playing", a->music_restarts);
    pa_music.after_request = a->music;
    pa_music.after_game = pa_music.game;
    pa_music.after_owner = a->folder;
    pa_music.after_due = pm_ms() + PA_MUSIC_FADE_MS + 20;
    pa_music.request = 0;
    pa_music.owner = 0;
}

/* the carrier's own list back and the game's music on, once ours has faded (any mode's tick) */
static PA_UNUSED void pa_music_after(void)
{
    if (pa_music.check_due && pm_ms() >= pa_music.check_due) {
        unsigned reqs[8], buses[8];
        int n = pm_sound_playing(reqs, buses, 8);
        pa_music.check_due = 0;
        if (n >= 0) pa_music_bus_note(reqs, buses, n, "a second after the end of a mode's music holds");
    }
    if (!pa_music.after_request || pm_ms() < pa_music.after_due) return;
    if (pm_sound_active(pa_music.after_request)) { pa_music.after_due = pm_ms() + 50; return; }
    pm_sound_sid(pa_music.after_request, 0);
    if (pa_music.after_game && pm_in_game())
        pm_log("own sound: music %u (%s's) faded out; the game's music %u %s", pa_music.after_request,
               pa_music.after_owner ? pa_music.after_owner : "?", pa_music.after_game,
               pm_sound(pa_music.after_game) ? "is playing again" : "could NOT be started again");
    else
        pm_log("own sound: music %u (%s's) faded out%s", pa_music.after_request,
               pa_music.after_owner ? pa_music.after_owner : "?",
               pa_music.after_game ? " (no game in play, the game's music is left to the game)" : "");
    pa_music.after_request = pa_music.after_game = 0;
    pa_music.check_due = pm_ms() + 1000;
    pa_music.nbus1 = -1;                  /* the look after the end always says what it found */
}

/* ---- start, end, tick ------------------------------------------------------------------------- */
/* The mode started: its carriers' priorities, its music, and its start clip half a second from now
 * (a clip started inside the shot that started the mode loses the one video surface to the game's
 * own clip for that shot; MODE_SDK.md "Clips race the game's own"). */
static PA_UNUSED void pa_start(struct pa_assets *a)
{
    pa_load(a);
    a->running = 1;
    if (!a->loaded) return;
    pa_priorities(a);
    pa_music_begin(a);
    a->clip_due = a->clip_start[0] ? pm_ms() + PA_CLIP_AFTER_MS : 0;
}

/* The mode ended (any way): its music fades and the game's comes back; a start clip still waiting
 * is dropped. Calls already playing (an end call) play out. */
static PA_UNUSED void pa_end(struct pa_assets *a)
{
    if (!a->running) return;
    a->running = 0;
    if (a->clip_due) {
        pm_log("own clip %s dropped before it played: the mode ended first", a->clip_start);
        a->clip_due = 0;
    }
    pa_music_finish(a);
}

static PA_UNUSED void pa_tick(struct pa_assets *a)
{
    unsigned long now = pm_ms();
    int i;
    if (a->clip_due && now >= a->clip_due) {
        a->clip_due = 0;
        pm_log("own clip %s %s", a->clip_start, pm_clip(a->clip_start) ? "started" : "NOT started (not in the bank?)");
    }
    for (i = 0; i < PA_STOPS_MAX; i++) {
        if (!a->stops[i].request || now < a->stops[i].due) continue;
        if (pm_sound_fade(a->stops[i].request, 40))
            pm_log("own sound: call %u stopped - its own sound is over, the rest of the record is silence",
                   a->stops[i].request);
        a->stops[i].request = 0;
    }
    for (i = 0; i < PA_WAITING_MAX; i++) {
        unsigned holder = 0;
        if (!a->waiting[i].request || now < a->waiting[i].due) continue;
        if (pa_try(a, a->waiting[i].request, a->waiting[i].prio, a->waiting[i].cue, 0, &holder)) {
            pm_log("own sound: call %s (%u) played (after waiting for the voice bus)", a->waiting[i].cue,
                   a->waiting[i].request);
            pa_stop_after(a, a->waiting[i].request, a->waiting[i].ms);
            a->waiting[i].request = 0;
            continue;
        }
        if (holder) a->waiting[i].holder = holder;
        if (now >= a->waiting[i].deadline) {
            if (a->waiting[i].holder)
                pm_log("own sound: call %s (%u) NOT played - the game's own speech %u held the voice bus",
                       a->waiting[i].cue, a->waiting[i].request, a->waiting[i].holder);
            else
                pm_log("own sound: call %s (%u) NOT played - the voice bus did not come free in time",
                       a->waiting[i].cue, a->waiting[i].request);
            a->waiting[i].request = 0;
        } else {
            a->waiting[i].due = now + 70;
        }
    }
    if (a->running) pa_music_under(a);
    pa_music_after();
}

#endif
