"""Lines of scene text Godzilla's own code lays out, whatever the card says (PAD-433).

Godzilla's screens (a battle's intro and background, an award, a multiball) are run by BDL
elements. When one loads its scene, its base class finds the Text of every node name on the
element's list and wraps it in a FlashyText, and FlashyText's constructor sets the Text's
VerticalAlignment to 1 (MIDDLE) and its ScaleToBounds to 1 (the words shrink to fit the box).
So those lines sit in the middle of their box and shrink to fit it on the machine, while the
card's own bytes say otherwise (every stock one says top).

Emulator-proven on Godzilla LE 1.16 (DragonRR: "the text is showing top aligned in pad and
center aligned in game"): the Gigan battle intro's BATTLE FOR TOKYO in a 220 px box drew at the
same rows stored top, middle and bottom, where the preview draws it in the middle. The
horizontal alignment is the card's own.

The table is read out of the game programs by ``tools/spike2_emu/bdl_texts.py`` (Godzilla
LE/Premium 1.16 and Pro 1.16 name the same lists): ``{scene: node paths}``, a scene by the
last two folders of its card path, a node by its dotted path from the scene's root (what the
game's own finder takes).
"""

#: what FlashyText sets on each listed Text
VALIGN = 1      # middle
FIT = 1         # ScaleToBounds


def scene_key(card_path):
    """The table's key for a scene's card path (``.../<40 hex>/<40 hex>/scene.radium``)."""
    parts = str(card_path or "").replace("\\", "/").rstrip("/").split("/")
    if parts and parts[-1].endswith(".radium"):
        parts = parts[:-1]
    return "/".join(parts[-2:])


def paths_for(card_path):
    """The node paths in the scene at *card_path* the game lays out itself (empty: none)."""
    return GAME_LAID_OUT.get(scene_key(card_path), ())


def mark(man, card_path):
    """Set the game's own layout on the Text objects of manifest *man* (:func:`scene_eval.
    manifest`, the scene at *card_path*) whose node the game lays out: ``valign`` middle,
    ``fit`` on, and ``game_layout`` True for the editor to say so.  In place; returns *man*."""
    want = set(paths_for(card_path))
    if not want or not man:
        return man
    objects = man.get("objects") or {}

    def walk(kids, prefix):
        for n in kids or ():
            path = prefix + [n.get("name") or ""]
            dotted = ".".join(path)
            for _s, oid in n.get("comps") or ():
                o = objects.get(str(oid)) or {}
                if o.get("kind") == "Text" and dotted in want:
                    o["valign"], o["fit"], o["game_layout"] = VALIGN, FIT, True
                if o.get("kind") in ("Sprite", "StreamingFlipbook"):
                    walk(o.get("kids"), path)
    walk((man.get("root") or {}).get("kids"), [])
    return man


def mark_scene(scene, card_path):
    """The same on a parsed :class:`scene_tree.Scene` (what Write lays the card's text out
    by): each listed Text's VerticalAlignment and ScaleToBounds as the game sets them.  The
    scene is changed in place, so only ever pass a copy that is not written back."""
    want = set(paths_for(card_path))
    if not want:
        return scene

    def walk(kids, prefix):
        for n in kids or ():
            path = prefix + [n.name]
            for c in n.components:
                if c.obj.kind == "Text" and ".".join(path) in want:
                    c.obj.body["tail"] = (FIT, VALIGN)
                if c.obj.kind in ("Sprite", "StreamingFlipbook"):
                    walk(c.obj.body.get("kids"), path)
    walk(scene.root.get("kids"), [])
    return scene


# Generated by tools/spike2_emu/bdl_texts.py from Godzilla LE/Premium 1.16 (godzilla_le/game
# sha1 ea8c6d36) and Pro 1.16 (godzilla_pro/game sha1 c9fbe1ba); do not edit by hand.
GAME_LAID_OUT = {
    "14f67f7abeefb9a76ba3ca1ea8a555f8f12771af/4cddb448f7601c950851b0bc5ebefd3fe50ec19c": (
        "Line1_Instance",
        "Title_Instance",
    ),
    "1678bb3a917ad1961524cb3c147e29ae5325ad46/1d0bc771d52a28549bf86f57bf06748be0645285": (
        "Lines_Textbox.Line1_Instance",
        "Lines_Textbox.Line2_Instance",
        "Title_Textbox.Title_Instance",
    ),
    "1678bb3a917ad1961524cb3c147e29ae5325ad46/d4539bcefb5fd69686a00c596f1c3d5eb53a0087": (
        "FleeJackpotMeter.Info_Instance",
        "FleeJackpotMeter.Number_Instance.Counter_Text_Instance",
        "FleeJackpotMeter.Title_Instance",
        "JackpotMeter.Info_Instance",
        "JackpotMeter.Number_Instance.Counter_Text_Instance",
        "JackpotMeter.Title_Instance",
        "Line_Instance",
    ),
    "307d5acf7feb0d4d2fa4e5f38df4e0d39d7edac9/087e47866fbf0797e8272c406458f3f5509928a1": (
        "Instructions_Instance",
        "Score_Instance",
    ),
    "307d5acf7feb0d4d2fa4e5f38df4e0d39d7edac9/5706ef33a2bab0537930112d998966bd4877385b": (
        "Line1_Instance",
        "Line2_Instance",
        "Score_Instance",
        "Title_Instance",
    ),
    "307d5acf7feb0d4d2fa4e5f38df4e0d39d7edac9/b983eb0bddcfc364ea1caa7bd72d8db0cf0eee78": (
        "Text_Textbox.Line1_Instance",
        "Text_Textbox.Line2_Instance",
    ),
    "3b278ea9e74a042719a58f33d9cbb403be99f4ca/51a2e49525907f901193b780b8dac3d0970ebcef": (
        "Line1_Instance",
        "Line2_Instance",
        "Title_Textbox.Title_Instance",
    ),
    "3b278ea9e74a042719a58f33d9cbb403be99f4ca/8500fbf19fd19556504c5db0136edf62d7de7ca3": (
        "Consecutive_Instance.Number_Instance",
        "Consecutive_Instance.Title_Instance",
        "Line1_Instance",
        "Line2_Instance",
        "Time_Instance.Seconds_Instance",
        "Time_Instance.Title_Instance",
    ),
    "3b278ea9e74a042719a58f33d9cbb403be99f4ca/9f020b25bfa96c19b6e52289d134c67349fba66f": (
        "Line1_Textbox.Line1_Instance",
        "Title_Textbox.Title_Instance",
    ),
    "3b278ea9e74a042719a58f33d9cbb403be99f4ca/ec99b0fa4e8984632222709f1211e3df27593aaa": (
        "Award_Textbox.Info_Instance",
        "Award_Textbox.Score_Instance",
        "Award_Textbox.Title_Instance",
        "Time_Instance.Seconds_Instance",
        "Time_Instance.Title_Instance",
    ),
    "477760ac3cc07d1aec810758d9fd83b7bc86ee72/39455fd1cfe1f4e2827846a64e58799c65f3a067": (
        "Info_Textbox.Info_Instance",
        "Time_Textbox.Time_Instance",
    ),
    "47785250c02bf74305bd54c4fac46695a6b98cb9/5194e25ace7e4b7ab68a17b16b4724a40a58df19": (
        "Line1_Instance",
        "Title_Instance",
    ),
    "47785250c02bf74305bd54c4fac46695a6b98cb9/5656825667f244211e377c6f50e81d9c9805edc1": (
        "Line1_Instance",
        "Title_Instance",
    ),
    "47785250c02bf74305bd54c4fac46695a6b98cb9/81e570eeb8648a0b4b7eb790fd7beb49af317df1": (
        "Line1_Instance",
        "Line2_Instance",
    ),
    "512ace0e7d8389ae4b362afbc0160cf492039181/4e1a2e794678404b5b02f5bf43e1145272253c9c": (
        "Line1_Instance",
        "Line2_Instance",
        "Line3_Instance",
    ),
    "56612469db1cc9faa5f5a485d7cb710535f906ce/db538e0957f696ad29885ea1588cf9db82d02c92": (
        "ArrowMeter.Number_Instance.Counter_Text_Instance",
        "ArrowMeter.Title_Instance",
        "Info_Instance",
        "Score.ScoreText.ScoreText_Instance",
        "SwitchMeter.Number_Instance.Counter_Text_Instance",
        "SwitchMeter.Title_Instance",
    ),
    "5b032f0f3367d035a92c727cdfe018781df6dfd9/902dc506c403173e6908fc5246ad1fb3e5177d81": (
        "Counter_Left_Instance",
        "Line1_Instance",
        "Line2_Left_Instance",
        "Score_Instance",
    ),
    "5b032f0f3367d035a92c727cdfe018781df6dfd9/a96b24080d4456f7a381d9918ba8ac1fa033780d": (
        "Lines_Textbox.Line1_Instance",
        "Lines_Textbox.Line2_Instance",
        "Lines_Textbox.Line3_Instance",
        "Title1_Textbox.Title1_Instance",
        "Title2_Textbox.Title2_Instance",
        "Title3_Textbox.Title3_Instance",
    ),
    "687f744516db566f57937aa3345db2e82c3e10ea/c8938395a96c29e78d006e0e592c65b68835c18d": (
        "Line1_Instance",
        "Score_Instance",
        "Title_Instance",
    ),
    "6bb2a76422a5f6a5c0354a79f19fc14ac4f6b2cb/1e1ca3a8e314b0e54a964491c8fb51f6688d6d76": (
        "Line1_Instance",
        "Score_Instance",
    ),
    "72152e02457805ffbbe99638c962137fe69d5112/6a8677471537cae5801fe522639d711fdeaea3ca": (
        "Title_Textbox.Title1_Instance",
        "Title_Textbox.Title2_Instance",
    ),
    "72152e02457805ffbbe99638c962137fe69d5112/73d32a6654211f5e39d5bbec77026225575ad427": (
        "Line1_Instance",
        "Line2_Instance",
    ),
    "78585115b02077cdd03f70a54c914d6a10dee632/6afd2988a5af8ca1cb1859bf4b98825d5100c780": (
        "Info_Instance",
        "Made_Instance.Next_Award_Instance",
        "Made_Instance.Number_Instance",
        "Made_Instance.Title_Instance",
        "Time_Instance.Seconds_Instance",
        "Time_Instance.Title_Instance",
        "Value_Instance.Number_Instance",
        "Value_Instance.Title_Instance",
    ),
    "81c210aaf9d4bf5172a278644e7a1d3fe8ef1bf7/314a7d11e964911ebb6b1e727a4b352690c0c4a5": (
        "BountyMeter.Number_Instance.Counter_Text_Instance",
        "BountyMeter.Title_Instance",
        "HiScoreLeft_Instance.Name_1_Instance",
        "HiScoreLeft_Instance.Name_2_Instance",
        "HiScoreLeft_Instance.Name_3_Instance",
        "HiScoreLeft_Instance.Score_1_Instance",
        "HiScoreLeft_Instance.Score_2_Instance",
        "HiScoreLeft_Instance.Score_3_Instance",
        "HiScoreLeft_Instance.Title_Instance",
        "HiScoreRight_Instance.Name_1_Instance",
        "HiScoreRight_Instance.Name_2_Instance",
        "HiScoreRight_Instance.Name_3_Instance",
        "HiScoreRight_Instance.Score_1_Instance",
        "HiScoreRight_Instance.Score_2_Instance",
        "HiScoreRight_Instance.Score_3_Instance",
        "HiScoreRight_Instance.Title_Instance",
        "Info_Instance",
        "ShotsMeter.Info_Instance",
        "ShotsMeter.Number_Instance.Counter_Text_Instance",
        "ShotsMeter.Title_Instance",
    ),
    "81c210aaf9d4bf5172a278644e7a1d3fe8ef1bf7/59a2e8b1f2018e464ea01524f68483d21d6aee65": (
        "BountyMeter.Number_Instance.Counter_Text_Instance",
        "BountyMeter.Title_Instance",
        "ChallengeTimeMeter.Number_Instance.Counter_Text_Instance",
        "ChallengeTimeMeter.Title_Instance",
        "Col1_Title_Instance",
        "Col1_Value_Instance",
        "Col2_Title_Instance",
        "Col2_Value_Instance",
        "Col3_Title_Instance",
        "Col3_Value_Instance",
        "Col4_Title_Instance",
        "Col4_Value_Instance",
        "HiScoreLeft_Instance.Name_1_Instance",
        "HiScoreLeft_Instance.Name_2_Instance",
        "HiScoreLeft_Instance.Name_3_Instance",
        "HiScoreLeft_Instance.Score_1_Instance",
        "HiScoreLeft_Instance.Score_2_Instance",
        "HiScoreLeft_Instance.Score_3_Instance",
        "HiScoreLeft_Instance.Title_Instance",
        "HiScoreRight_Instance.Name_1_Instance",
        "HiScoreRight_Instance.Name_2_Instance",
        "HiScoreRight_Instance.Name_3_Instance",
        "HiScoreRight_Instance.Score_1_Instance",
        "HiScoreRight_Instance.Score_2_Instance",
        "HiScoreRight_Instance.Score_3_Instance",
        "HiScoreRight_Instance.Title_Instance",
    ),
    "81c210aaf9d4bf5172a278644e7a1d3fe8ef1bf7/aac1134f04d1c7b5be51757c4e2dcada48d29f7c": (
        "Instructions1.Line1_Instance",
        "Instructions1.Line2_Instance",
        "Instructions2.Line1_Instance",
        "Instructions2.Line2_Instance",
        "Instructions2.Line3_Instance",
    ),
    "81c210aaf9d4bf5172a278644e7a1d3fe8ef1bf7/c889dc82993355ad5356af43a172e7fb7e957ddb": (
        "Total_Textbox.TextTitle",
        "Total_Textbox.TextValue1",
    ),
    "94891eb7b796b6fada1cbff1c18ef0a42e68b5b4/3996f13a3918216900aa39b3f65279bb4da89d6e": (
        "Line1_Instance",
        "Line2_Instance",
        "Title_Textbox.Title_Instance",
    ),
    "99cd5ccc01720c43f3d3bc1ccecd9cb40ae3f7e4/49ac2e4041ae16eb56b2cf5484936ce1f6f271dd": (
        "Counter_Center_Instance",
        "Counter_Left_Instance",
        "Counter_Right_Instance",
        "Line1_Center_Instance",
        "Line1_Instance",
        "Line1_Left_Instance",
        "Line1_Right_Instance",
        "Line2_Center_Instance",
        "Line2_Left_Instance",
        "Line2_Right_Instance",
    ),
    "99cd5ccc01720c43f3d3bc1ccecd9cb40ae3f7e4/723628da0d4bdf6e95f1647dcfd6b04c9df52654": (
        "Lines_Textbox.Line1_Instance",
        "Lines_Textbox.Line2_Instance",
        "Lines_Textbox.Line3_Instance",
        "Title1_Textbox.Title1_Instance",
        "Title2_Textbox.Title2_Instance",
        "Title3_Textbox.Title3_Instance",
    ),
    "9ede9694be6856f8da961d23fbc57ba2a473b7c6/e5d4285c24d43844a61df9fedc3347779b684748": (
        "Col1_Title_Instance",
        "Col1_Value_Instance",
        "Col2_Title_Instance",
        "Col2_Value_Instance",
        "Col3_Title_Instance",
        "Col3_Value_Instance",
        "Col4_Title_Instance",
        "Col4_Value_Instance",
        "FlipsChange.FlipsChangeAnim.FlipsChange_Text",
        "FlipsMeter.Info_Instance",
        "FlipsMeter.Number_Instance.Counter_Text_Instance",
        "FlipsMeter.Title_Instance",
        "Score.ScoreText.ScoreText_Instance",
        "ShotsMeter.Info_Instance",
        "ShotsMeter.Number_Instance.Counter_Text_Instance",
        "ShotsMeter.Title_Instance",
    ),
    "9fb470d4e77248ffd13c7830adfe66fdea70ed87/017aa70dbac986280b47795bc96305b155aed375": (
        "Line1_Instance",
        "Score_Instance",
        "Title_Instance",
    ),
    "9fb470d4e77248ffd13c7830adfe66fdea70ed87/e99a0ffd324e705238dfac657cf05c47c1663905": (
        "Line1_Instance",
        "Score_Instance",
    ),
    "9fb470d4e77248ffd13c7830adfe66fdea70ed87/fc9aaa47e62cbdf22cb92b04f45735c4eb863ce3": (
        "Line1_Instance",
        "Line2_Instance",
        "Title_Textbox.Title_Instance",
    ),
    "a248977badd032e625ee2480e8cc6d0b2f645d1f/345c2cce38a2fd971bdd09ec17dbe9eaa3c5cc1a": (
        "Counter_Left_Instance",
        "Line1_Instance",
        "Line2_Left_Instance",
    ),
    "a248977badd032e625ee2480e8cc6d0b2f645d1f/e5793bce06a18e840f98aca8e14dbdbd0547ab60": (
        "Lines_Textbox.Line1_Instance",
        "Lines_Textbox.Line2_Instance",
        "Lines_Textbox.Line3_Instance",
        "Title1_Textbox.Title1_Instance",
        "Title2_Textbox.Title2_Instance",
        "Title3_Textbox.Title3_Instance",
    ),
    "acbfac6e7d7f808fcbc9e3e046025e4fa4950b53/4beaae686c58cb17bb8d530f12db5fd05d8988fe": (
        "Counter_Left_Instance",
        "Line1_Instance",
        "Line2_Left_Instance",
    ),
    "acbfac6e7d7f808fcbc9e3e046025e4fa4950b53/693a34a3e35163f5f7158386d5cd80f05b27b5a1": (
        "Lines_Textbox.Line1_Instance",
        "Lines_Textbox.Line2_Instance",
        "Lines_Textbox.Line3_Instance",
        "Title1_Textbox.Title1_Instance",
        "Title2_Textbox.Title2_Instance",
        "Title3_Textbox.Title3_Instance",
    ),
    "aedc9ebca136847fcb041ab9e49fd5624f6e7d21/59e36388f1ecd2cac796054ca93f76671af7fad1": (
        "Info_Instance",
        "Score_Instance",
        "Title2_Textbox.Title2_Textbox_Instance",
        "Title_Instance",
    ),
    "aedc9ebca136847fcb041ab9e49fd5624f6e7d21/f5cd71d1314e4039049032911fd2a2cc53c4f8de": (
        "NewX_Textbox.NewX_Instance",
        "OldX_Textbox.OldX_Instance",
        "Title_Textbox.Title_Instance",
    ),
    "c65ecc5e2f5769bdc59851eb951a1c781b53deb8/283eedebcb7b53499d1dd7a97fe01469f67b0e5b": (
        "Line1_Instance",
        "Title_Instance",
    ),
    "c65ecc5e2f5769bdc59851eb951a1c781b53deb8/e19f1b5fd7a3ca41e2945839f4d35bb5bd6ab597": (
        "Lines_Textbox.Line1_Instance",
        "Lines_Textbox.Line2_Instance",
        "Title_Textbox.Title_Instance",
    ),
    "d3ab0cedcb106ca55ad85a76cfcd2c06462be4d9/0614ce277fd348d1b42f4d3d52fee8530ed946d1": (
        "Line1_Instance",
        "Title_Instance",
    ),
    "d3ab0cedcb106ca55ad85a76cfcd2c06462be4d9/b00ce2363b5a729e32704cc26cff390544815593": (
        "Line1_Instance",
        "Line2_Instance",
        "Line3_Instance",
    ),
    "de282fdccc32be1878ee1024247c24f5fe693d68/cca06e41f719081a7d699474ef95275c271e4652": (
        "InfoText.InfoText_Symbol.InfoText_Instance",
        "JackpotValue.JackpotValue_Symbol.JackpotValue_Instance",
    ),
    "e6525192bf11c4da8b7cfdc491b509823d095677/ce02c662b192be654acdfba591995e21cdbda214": (
        "Lines_Textbox.Line1_Instance",
        "Lines_Textbox.Line2_Instance",
        "Title_Textbox.Title_Instance",
    ),
    "e6525192bf11c4da8b7cfdc491b509823d095677/d39cef96c4cbe8a06ff39998de4667b91421417e": (
        "JackpotMeter.Info_Instance",
        "JackpotMeter.Number_Instance.Counter_Text_Instance",
        "JackpotMeter.Title_Instance",
        "Line_Instance",
        "SwitchesMeter.Info_Instance",
        "SwitchesMeter.Number_Instance.Counter_Text_Instance",
        "SwitchesMeter.Title_Instance",
    ),
    "fb84341a4f335f98b218a0a03136f3c1e6d88a29/8a7bff7b21ef41bf51242d07fa6f1156a1f8caa9": (
        "Title_Instance",
        "Value_Instance",
    ),
    "fb84341a4f335f98b218a0a03136f3c1e6d88a29/a6d9d01271c6911dc40cc452f13565d0a7567f83": (
        "Line1_Instance",
        "Line2_Instance",
    ),
}
