"""The game's own modes for any Spike 2 build: a hand table, or one generated from the program.

CONTRACT (title_reader calls this; keep the signature):

    ensure_table(elf, game, version, progress=None, cancel=None) -> TableResult

``progress(fraction, text)`` runs 0..1; ``cancel()`` returning True stops the work with
:class:`.title_reader.Cancelled`. The order is:

1. a HAND table (:mod:`.stock_mode_tables`) for this exact program - it always wins;
2. a table GENERATED earlier on this machine for this program (by its SHA-1);
3. a program :data:`KNOWN_STOCK` names (as Stern shipped it): a table generated NOW from it
   by the readers in :mod:`.stock_scan_cpp` (C++ rule titles) or :mod:`.stock_scan_c`
   (plain-C titles), a second or two cold, and saved - never another program's table;
4. any other program: the table of the same game and version when this program is that build
   with numbers this app changed in it (``stock_modes.identify``'s instruction or settings
   route) - a card the app already wrote is never read as stock;
5. a program holding this app's own text segment, or one that isn't the stock program of a
   build :data:`KNOWN_STOCK` names, whose original hasn't been read: refused, with a note
   asking for the original card once;
6. a build the app doesn't know at all: read, and the notes say its numbers are the card's.

Generated tables are kept in :func:`user_tables_dir` as ``<sha1>.r<READER_REV>.txt`` with an
``index.json`` keyed by the program's SHA-1 (every kept table is listed, so two programs of
one build never displace each other), and :func:`.stock_modes.tables` lists them after the
hand tables - tables read from a known stock program first - so ``table_for``, ``identify``
and every caller of those (the tab's dialog, the Write scan, the engine's Write) see them
with no change. Raising :data:`READER_REV` makes every older generated table stale: it is
generated again the next time its card is read.

A STOCK PROGRAM. A table records the numbers it reads as the game's own, so it must be read
from a program as Stern shipped it. A Write of the game's own numbers changes only
instruction words and setting defaults, so a written card has no mark of its own: what tells
it apart is that its SHA-1 isn't the one :data:`KNOWN_STOCK` lists for its build (step 5).
"""

import hashlib
import json
import os
import struct
import threading
import time
from dataclasses import dataclass

#: the generated tables' revision: a table generated by an older reader is generated again
#: (2: tail calls end a function, a word read twice or an unnamed timer number is read-only,
#: shared words carry their count, the index is keyed by SHA-1)
READER_REV = 2

#: game programs as Stern shipped them (sha1 -> "game version"), every build this app has seen
KNOWN_STOCK = {
    "1be5fbb9cf15af2f7f780ba289e44da85569688c": "aerosmith_le 1.15.0",
    "c8b80957f10ad88a297b7970ece52aa5a36834d2": "avengers_infinity_le 1.09.0",
    "4e11096f5e2d4ad24a5eb0fc9bee4722b2a06908": "batman 1.13.0",
    "89bdc7b3f2ed1eaf6b8b6213ab1b199fbb56b91d": "beatles 1.29.0",
    "d1c1c8cdd1dfe3883d220f75e6c0411aa8419652": "deadpool_le 1.14.0",
    "dd7876d6a16361522f4e75b858b6dc2db06a13b4": "deadpool_pro 1.16.0",
    "c3f5d99793b3c2a29e98b62481bb83448af3ced7": "dungeons_and_dragons_le 1.00.0",
    "8e8a206697dde2382e20bc8654acd8cb9df7f49d": "elvira3 1.13.0",
    "ffe498952469d35b997f7cedc38405b018d47117": "foo_fighters_le 1.04.0",
    "ea8c6d36f130bfe1421b36c0a071bc66c9be4e99": "godzilla_le 1.16.0",
    "08d502998706d327bfbb6ea5f92ac0cee76be63b": "godzilla_pro 1.15.0",
    "c9fbe1ba3a4f83a93259402fa2abee8f2bdafdb7": "godzilla_pro 1.16.0",
    "5f0ae92299969d73d0430d1bd43a5c36006186d3": "guardians_le 1.14.0",
    "53a80db3967517380866945587eeda0b33519124": "iron_maiden_le 1.16.0",
    "c870f3bc6c56333dae1b27766c6dcdce5a9e8ba2": "james_bond_60th_le 1.11.0",
    "0e9d539aa6a2496469b638ba12191075f79fcef3": "james_bond_le 1.06.0",
    "4fb9eaa46c4684372c5b0b34021f88c639ed952d": "jaws_le 1.02.0",
    "c5f0dbdf995adfdb9c783b604fd1a8eec6fcc300": "john_wick_le 1.01.0",
    "a55d58f0c6591d2b7664ce8700b7b3a9f51e2e0d": "jurassic_park_le 1.16.0",
    "2edcffd1f0383289f1635c98f25c0d5fe06b7655": "jurassic_park_the_pin 1.05.0",
    "034964e23f5e94a4f48e0f1e0a448834c4c4cc9c": "king_kong_le 0.97.0",
    "b6fe09cd662926f85353466b4115963e66e19f6d": "led_zeppelin_le 1.22.0",
    "c7d18db97aa783fc1af2e8ce1a4c646f4ecdbb9a": "led_zeppelin_pro 1.22.0",
    "1027924b12c1673e5d8f7e1b3df00485c2b5fc1f": "mando_le 1.44.0",
    "f5d1b36550b44555ff7467ab7ac38e67ab0c874d": "metallica_spike 1.03.0",
    "aad880bbb91d1d4989dd17c5fd795cfe0170ed59": "munsters_le 1.28.0",
    "60c8026e56b0123b9300934405e990fda4d6b500": "rush_le 1.18.0",
    "ee9ca85b9e074b02ab9d6a54af226c8073c43bf9": "star_wars_elg 1.10.0",
    "ddbf86a53a4420b53910f2f604753513b10c58b5": "star_wars_le 1.30.0",
    "6078cfa32b554b0ab1b3380202353c6d87b1ffc1": "stranger_things_le 1.12.0",
    "5684a7e0f1ab8c55f7d7ee389923e4283907e20a": "sword_of_rage_le 1.18.0",
    "89c916f82269e8a9d8d060ba2708cdec1cef02e5": "turtles_le 1.59.0",
    "8dd4bb737fb3dabaee44f53f9d4703a953ab14e8": "turtles_pro 1.58.0",
    "9af74699c9be1196c1e1f871006a961bbd6471fe": "turtles_pro 1.59.0",
    "0d33470241a7143cfe7b9e39dbcdea83ba6a5b95": "uncanny_xmen_le 0.98.0",
    "43ba72d8b82d8a912c3c28c4a7b46ac77d79680a": "venom_le 1.07.0",
}

INDEX = "index.json"
INDEX_FORMAT = 2
NO_MODES = "No modes of the game's own were found in this game program."
#: the caveat of a table read from a program the app has not seen from Stern
UNKNOWN_BUILD = ("This build isn't one the app has seen from Stern, so the numbers shown as the "
                 "game's own are the ones on this card.")


@dataclass
class TableResult:
    build: object = None      # a stock_modes.Build, or None
    origin: str = ""          # "hand" | "generated" | ""
    notes: tuple = ()


def user_tables_dir():
    """Where tables generated on this machine are kept."""
    from .title_reader import cache_dir
    return cache_dir("stock_tables")


def table_path(sha1, rev=READER_REV):
    return os.path.join(user_tables_dir(), "%s.r%d.txt" % (sha1, rev))


# ---- generating --------------------------------------------------------------------------------
def generate(elf, game, version, progress=None, cancel=None):
    """``(table text, info)`` for the game program *elf* (bytes): the C++ reader on a title
    with a C++ rule manager, the plain-C reader otherwise. *info* = ``{"family", "modes",
    "rows", "seconds"}``. Raises :class:`.stock_scan.ScanError` when the program can't be
    read, :class:`.title_reader.Cancelled` when *cancel* says so."""
    from . import stock_scan as S
    from . import stock_scan_c, stock_scan_cpp
    from .title_reader import Cancelled
    say = progress or (lambda f, t="": None)
    t0 = time.monotonic()
    say(0.0, "Reading the game program")
    prog = S.Program(elf)
    if cancel is not None and cancel():
        raise Cancelled()
    say(0.03, "Reading the program's classes")
    model = S.class_model(prog)
    if stock_scan_cpp.family(model):
        reading = stock_scan_cpp.read(prog, model, step=lambda f, t="": say(0.05 + 0.9 * f, t),
                                      cancel=cancel)
    else:
        reading = stock_scan_c.read(prog, step=lambda f, t="": say(0.05 + 0.9 * f, t),
                                    cancel=cancel)
    seconds = time.monotonic() - t0
    head = ["generated by this app from the game program (reader revision %d, %s rules)"
            % (READER_REV, {"c": "plain-C"}.get(reading.family, reading.family))]
    text = S.table_text(game, version, prog.sha1, reading, head)
    info = {"family": reading.family, "modes": len(reading.modes),
            "rows": sum(len(m.rows) for m in reading.modes), "seconds": seconds}
    say(0.97, "Saving")
    return text, info


def stock_state(elf, sha1=None):
    """``("known" | "ours" | "unknown", words)``: whether *elf* is a program as Stern shipped
    it (a build this app knows), one this app changed (it holds the app's extension segment),
    or one it can't tell."""
    sha1 = sha1 or hashlib.sha1(elf).hexdigest()
    if sha1 in KNOWN_STOCK:
        return "known", "a build this app knows as Stern shipped it (%s)" % KNOWN_STOCK[sha1]
    from .progreloc import EXT_MAGIC
    if EXT_MAGIC in elf:
        return "ours", ("this card's game program was changed by this app (it holds the "
                        "app's own text segment)")
    return "unknown", "a build this app hasn't seen from Stern"


def known_build(game, version):
    """The ``"<game> <version>"`` of a build :data:`KNOWN_STOCK` names for this title and
    version (versions compared as the tables compare them: ``1.59`` is ``1.59.0``), or None."""
    from .stock_modes import version_key
    want = version_key(version)
    for name in KNOWN_STOCK.values():
        g, _sp, v = name.partition(" ")
        if g == game and version_key(v) == want:
            return name
    return None


# ---- the cache -------------------------------------------------------------------------------------
_LOCK = threading.RLock()
_CACHE = {"index_key": None, "builds": [], "parsed": {}}


def _index_file():
    return os.path.join(user_tables_dir(), INDEX)


def load_index():
    """``{sha1: {"game", "version", "rev", "stock", "made"}}`` (``{}`` on any trouble; an
    index of an older format lists nothing)."""
    try:
        with open(_index_file(), "r", encoding="utf-8") as f:
            data = json.load(f)
        if not isinstance(data, dict) or data.get("format") != INDEX_FORMAT:
            return {}
        builds = data.get("builds")
        return {k: v for k, v in builds.items() if isinstance(v, dict)} \
            if isinstance(builds, dict) else {}
    except (OSError, ValueError):
        return {}


def _write_atomic(path, text):
    tmp = "%s.%d.%d.tmp" % (path, os.getpid(), threading.get_ident())
    try:
        with open(tmp, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            try:
                os.remove(tmp)
            except OSError:
                pass


def save_table(text, game, version, sha1, stock):
    """Keep a generated table and list it in the index under its program's SHA-1. Raises
    OSError when the folder can't be written."""
    with _LOCK:
        os.makedirs(user_tables_dir(), exist_ok=True)
        _write_atomic(table_path(sha1), text)
        idx = load_index()
        idx[sha1] = {"game": game, "version": str(version), "rev": READER_REV, "stock": stock,
                     "made": time.strftime("%Y-%m-%d %H:%M:%S")}
        _write_atomic(_index_file(), json.dumps({"format": INDEX_FORMAT, "builds": idx},
                                                indent=1, sort_keys=True))
        _CACHE["index_key"] = None


def _parse_file(path):
    from . import stock_modes
    try:
        st = os.stat(path)
    except OSError:
        return None
    key = (st.st_mtime_ns, st.st_size)
    with _LOCK:
        got = _CACHE["parsed"].get(path)
        if got and got[0] == key:
            return got[1]
        try:
            with open(path, "r", encoding="utf-8") as f:
                builds = stock_modes.parse(f.read())
        except (OSError, ValueError, UnicodeDecodeError):
            builds = []
        b = builds[0] if len(builds) == 1 else None
        _CACHE["parsed"][path] = (key, b)
        return b


def cached_builds():
    """Every generated table of the current revision listed in the index, as
    :class:`.stock_modes.Build` (parsed once per file change). ``[]`` on any trouble."""
    try:
        path = _index_file()
        st = os.stat(path)
        key = (path, st.st_mtime_ns, st.st_size)
    except OSError:
        return []
    with _LOCK:
        if _CACHE["index_key"] == key:
            return list(_CACHE["builds"])
        out = []
        idx = load_index()
        # a table read from a program Stern shipped comes before one read from a program the
        # app doesn't know, so the first table of a title and version is the stock one
        for sha1 in sorted(idx, key=lambda k: (idx[k].get("stock") != "known",
                                               str(idx[k].get("game")), k)):
            if idx[sha1].get("rev") != READER_REV:
                continue
            b = _parse_file(table_path(sha1))
            if b is not None and b.sha1 == sha1 and b.modes:
                out.append(b)
        _CACHE["index_key"], _CACHE["builds"] = key, out
        return list(out)


def cached_table(sha1):
    """The generated table for this program, when one of the current revision is kept."""
    b = _parse_file(table_path(sha1))
    return b if b is not None and b.sha1 == sha1 else None


def older_tables(sha1):
    """The tables OLDER readers kept for this program (``<sha1>.r<rev>.txt`` below
    :data:`READER_REV`, newest first). A project's staged row keys are read through them
    after an app update raised the revision (``stock_modes.resolve_keys``), so they are
    never deleted by a newer reader."""
    out = []
    for rev in range(READER_REV - 1, 0, -1):
        b = _parse_file(table_path(sha1, rev))
        if b is not None and b.sha1 == sha1:
            out.append(b)
    return out


# ---- the operator menu's words for a table's settings ---------------------------------------------
def captions_for(elf, build, sha1=None):
    """``{AD_NAME: caption}``: what the operator menu prints for each setting *build*'s rows
    name (``adjustments.menu_label``: the Defaults tab's words), read from the game program
    *elf* once and kept beside the tables as ``<sha1>.captions.json``. ``{}`` on any trouble
    (the tab then words a setting from its name)."""
    if build is None:
        return {}
    names = sorted(build.adjustment_numbers())
    if not names:
        return {}
    sha1 = sha1 or hashlib.sha1(bytes(elf)).hexdigest()
    path = os.path.join(user_tables_dir(), "%s.captions.json" % sha1)
    try:
        with open(path, "r", encoding="utf-8") as f:
            kept = json.load(f)
        if isinstance(kept, dict) and all(n in kept for n in names):
            return {n: str(kept[n]) for n in names if kept[n]}
    except (OSError, ValueError):
        pass
    try:
        from . import adjustments as A
        table = A.AdjustmentTable(bytes(elf))
        out = {n: A.menu_label(table, table.by_name[n]) for n in names if n in table.by_name}
    except Exception:                               # noqa: BLE001 - words only
        return {}
    try:
        _write_atomic(path, json.dumps({n: out.get(n, "") for n in names}, indent=1,
                                       sort_keys=True))
    except OSError:
        pass
    return {n: c for n, c in out.items() if c}


# ---- the contract ----------------------------------------------------------------------------------
def ensure_table(elf, game, version, progress=None, cancel=None):
    """:class:`TableResult` for the game program *elf*: hand table, cached table, a table
    generated from a stock program, the original's table for a card this app changed, or a
    note saying why there is none (see the module)."""
    from . import stock_modes as SM
    from .stock_scan import ScanError
    from .title_reader import Cancelled
    say = progress or (lambda f, t="": None)

    def check():
        if cancel is not None and cancel():
            raise Cancelled()

    def done(result):
        say(1.0, "")
        return result

    elf = bytes(elf)
    sha1 = hashlib.sha1(elf).hexdigest()
    say(0.0, "Looking for this build's table")
    hand = SM.hand_tables()
    for b in hand:
        if b.sha1 == sha1:
            return done(TableResult(build=b, origin="hand"))
    try:
        img = SM.ElfImage(elf)
    except (SM.StockModeError, ValueError, struct.error) as e:
        return done(TableResult(notes=("The game program can't be read: %s." % e,)))
    state, why = stock_state(elf, sha1)
    b = cached_table(sha1)
    if b is not None and state != "known" and (state == "ours" or known_build(game, version)):
        # kept from a program that is not Stern's (one this app changed, or not the stock
        # program of a build the app now knows): never served as the game's own numbers;
        # the original's table or the refusal below decides
        b = None
    if b is not None:
        if not b.modes:
            return done(TableResult(notes=(NO_MODES,)))
        if sha1 not in load_index():
            # a table kept without its index line (the index was lost): list it again
            try:
                with open(table_path(sha1), "r", encoding="utf-8") as f:
                    save_table(f.read(), game, version, sha1, state)
            except OSError:
                pass
        # the caveat of a program the app has not seen from Stern stays with its table
        return done(TableResult(build=b, origin="generated",
                                notes=(UNKNOWN_BUILD,) if state == "unknown" else ()))
    check()
    if state != "known":
        # a card this app already wrote numbers into: the table of its original
        # (never this very program's own kept table: that is not its original's)
        cands = [x for x in hand + cached_builds() if x.same_title(game, version)
                 and x.sha1 != sha1]
        if cands:
            found, _how, _why = SM.identify(img, cands, game, version)
            if found is not None:
                return done(TableResult(
                    build=found, origin="hand" if found in hand else "generated",
                    notes=("This card's game program holds numbers this app changed; the "
                           "table read from the original %s is used." % found.id,)))
        if state == "ours":
            return done(TableResult(notes=(
                "The game's own modes can't be read from this card: %s, so its numbers "
                "aren't the game's own. Open the original card once to read them." % why,)))
        known = known_build(game, version)
        if known is not None:
            return done(TableResult(notes=(
                "The game's own modes can't be read from this card: its game program isn't "
                "the one Stern shipped as %s (it may hold numbers this app changed), so its "
                "numbers can't be taken as the game's own. Open the original %s card once, "
                "then this one." % (known, known),)))
    check()
    try:
        text, info = generate(elf, game, version,
                              progress=lambda f, t="": say(0.02 + 0.95 * f, t), cancel=cancel)
    except (ScanError, ValueError, struct.error, IndexError) as e:
        return done(TableResult(notes=("The game's own modes can't be read from this game "
                                       "program: %s." % e,)))
    check()
    notes = []
    try:
        save_table(text, game, version, sha1, state)
        b = cached_table(sha1)
    except OSError as e:
        notes.append("The table couldn't be kept on this computer (%s); it is read again "
                     "next time." % (e.strerror or e))
        builds = SM.parse(text)
        b = builds[0] if builds else None
    if not info["modes"] or b is None:
        return done(TableResult(notes=tuple([NO_MODES] + notes)))
    notes.insert(0, "Read %d of the game's own modes from the program in %.1f s." % (
        info["modes"], info["seconds"]))
    if state == "unknown":
        notes.append(UNKNOWN_BUILD)
    return done(TableResult(build=b, origin="generated", notes=tuple(notes)))
