"""Data East / Sega / Stern classic-DMD game database.

Auto-generated from PinMAME ``src/wpc/degames.c`` (Data East +
early-Sega DMD hardware) and ``src/wpc/segames.c`` (Sega/Stern
Whitestar).  Per family we keep the PARENT romset's ROM filenames;
``filename_hints`` is the romset family prefix, matched against the
user's zip basename.  Detection (see :mod:`.formats`) scores each game
by how many of its catalogued ROM names appear in the zip plus a hint
bonus.  ``manufacturer`` is the brand each entry exposes (Data East /
Sega / Stern); extraction is capture-only via libpinmame.
"""

GAME_DB = {
    "batman": {
        "display": 'Batman',
        "family": 'btmn',
        "manufacturer": 'Data East',
        "year": 1991,
        "dmd": '128x16',
        "game_roms": ['batcpub5.103', 'batcpuc5.103'],
        "dmd_roms": ['batdsp.102'],
        "sound_roms": ['batman.u7', 'batman.u17', 'batman.u21'],
        "filename_hints": ['btmn'],
    },
    "checkpoint": {
        "display": 'Checkpoint',
        "family": 'ckpt',
        "manufacturer": 'Data East',
        "year": 1991,
        "dmd": '128x16',
        "game_roms": ['chkpntb5.107', 'chkpntc5.107'],
        "dmd_roms": ['chkpntds.512'],
        "sound_roms": ['chkpntf7.rom', 'chkpntf6.rom', 'chkpntf5.rom'],
        "filename_hints": ['ckpt'],
    },
    "teenage_mutant_ninja_turtles": {
        "display": 'Teenage Mutant Ninja Turtles',
        "family": 'tmnt',
        "manufacturer": 'Data East',
        "year": 1991,
        "dmd": '128x16',
        "game_roms": ['tmntb5a.104', 'tmntc5a.104'],
        "dmd_roms": ['tmntdsp.104'],
        "sound_roms": ['tmntf7.rom', 'tmntf6.rom', 'tmntf4.rom'],
        "filename_hints": ['tmnt'],
    },
    "aaron_spelling": {
        "display": 'Aaron Spelling',
        "family": 'aar',
        "manufacturer": 'Data East',
        "year": 1992,
        "dmd": '128x32',
        "game_roms": ['as512cpu.bin'],
        "dmd_roms": ['asdspu12.bin', 'asdspu14.bin'],
        "sound_roms": ['assndu7.bin', 'assndu17.bin', 'assndu21.bin'],
        "filename_hints": ['aar'],
    },
    "hook": {
        "display": 'Hook',
        "family": 'hook',
        "manufacturer": 'Data East',
        "year": 1992,
        "dmd": '128x16',
        "game_roms": ['hokcpua.408'],
        "dmd_roms": ['hokdspa.401'],
        "sound_roms": ['hooksnd.u7', 'hook-voi.u17', 'hook-voi.u21'],
        "filename_hints": ['hook'],
    },
    "lethal_weapon_3": {
        "display": 'Lethal Weapon 3',
        "family": 'lw3',
        "manufacturer": 'Data East',
        "year": 1992,
        "dmd": '128x32',
        "game_roms": ['lw3cpuu.208'],
        "dmd_roms": ['lw3drom1.a26', 'lw3drom0.a26'],
        "sound_roms": ['lw3u7.dat', 'lw3u17.dat', 'lw3u21.dat'],
        "filename_hints": ['lw3'],
    },
    "michael_jordan": {
        "display": 'Michael Jordan',
        "family": 'mj',
        "manufacturer": 'Data East',
        "year": 1992,
        "dmd": '128x32',
        "game_roms": ['MJcpuc5.bin'],
        "dmd_roms": ['MJdsp0.bin'],
        "sound_roms": ['MJsndu7.bin', 'MJsndu17.bin', 'MJsndu21.bin'],
        "filename_hints": ['mj'],
    },
    "star_trek_25th_anniversary": {
        "display": 'Star Trek 25th Anniversary',
        "family": 'trek',
        "manufacturer": 'Data East',
        "year": 1992,
        "dmd": '128x16',
        "game_roms": ['trekcpuu.201'],
        "dmd_roms": ['trekdspa.109'],
        "sound_roms": ['trek.u7', 'trek.u17', 'trek.u21'],
        "filename_hints": ['trek'],
    },
    "adventures_of_rocky_and_bullwinkle_and_friends": {
        "display": 'The Adventures of Rocky and Bullwinkle and Friends',
        "family": 'rab',
        "manufacturer": 'Data East',
        "year": 1993,
        "dmd": '128x32',
        "game_roms": ['rabcpua.320'],
        "dmd_roms": ['rbdspa.300'],
        "sound_roms": ['rab.u7', 'rab.u17', 'rab.u21'],
        "filename_hints": ['rab'],
    },
    "jurassic_park": {
        "display": 'Jurassic Park',
        "family": 'jupk',
        "manufacturer": 'Data East',
        "year": 1993,
        "dmd": '128x32',
        "game_roms": ['jpcpua.513'],
        "dmd_roms": ['jpdspa.510'],
        "sound_roms": ['jpu7.dat', 'jpu17.dat', 'jpu21.dat'],
        "filename_hints": ['jupk'],
    },
    "last_action_hero": {
        "display": 'Last Action Hero',
        "family": 'lah',
        "manufacturer": 'Data East',
        "year": 1993,
        "dmd": '128x32',
        "game_roms": ['lahcpua.112'],
        "dmd_roms": ['lahdispa.106'],
        "sound_roms": ['lahsnd.u7', 'lahsnd.u17', 'lahsnd.u21'],
        "filename_hints": ['lah'],
    },
    "tales_from_the_crypt": {
        "display": 'Tales from the Crypt',
        "family": 'tftc',
        "manufacturer": 'Data East',
        "year": 1993,
        "dmd": '128x32',
        "game_roms": ['tftccpua.303'],
        "dmd_roms": ['tftcdspa.301'],
        "sound_roms": ['sndu7.dat', 'sndu17.dat', 'sndu21.dat'],
        "filename_hints": ['tftc'],
    },
    "guns_n_roses": {
        "display": "Guns N' Roses",
        "family": 'gnr',
        "manufacturer": 'Data East',
        "year": 1994,
        "dmd": '128x32',
        "game_roms": ['gnrcpua.300'],
        "dmd_roms": ['gnrdispa.300'],
        "sound_roms": ['gnru7.snd', 'gnru17.snd', 'gnru21.snd', 'gnru36.snd', 'gnru37.snd'],
        "filename_hints": ['gnr'],
    },
    "tommy_pinball_wizard_the_whos": {
        "display": "Tommy Pinball Wizard, The Who's",
        "family": 'tomy',
        "manufacturer": 'Data East',
        "year": 1994,
        "dmd": '128x32',
        "game_roms": ['tomcpua.400'],
        "dmd_roms": ['tommydva.400'],
        "sound_roms": ['tommysnd.u7', 'tommysnd.u17', 'tommysnd.u21', 'tommysnd.u36', 'tommysnd.u37'],
        "filename_hints": ['tomy'],
    },
    "wwf_royal_rumble": {
        "display": 'WWF Royal Rumble',
        "family": 'wwfr',
        "manufacturer": 'Data East',
        "year": 1994,
        "dmd": '128x32',
        "game_roms": ['wwfcpua.106'],
        "dmd_roms": ['wwfdispa.102'],
        "sound_roms": ['wfsndu7.512', 'wfsndu17.400', 'wfsndu21.400', 'wfsndu36.400'],
        "filename_hints": ['wwfr'],
    },
    "star_wars": {
        "display": 'Star Wars',
        "family": 'stwr',
        "manufacturer": 'Data East',
        "year": 2012,
        "dmd": '128x32',
        "game_roms": ['starcpua.104'],
        "dmd_roms": ['sw4mrom.a15'],
        "sound_roms": ['s-wars.u7', 's-wars.u17', 's-wars.u21'],
        "filename_hints": ['stwr'],
    },
    "frankenstein_mary_shelleys": {
        "display": "Frankenstein, Mary Shelley's",
        "family": 'frankst',
        "manufacturer": 'Sega',
        "year": 1994,
        "dmd": '192x64',
        "game_roms": ['franka.103'],
        "dmd_roms": ['frdspr0a.103', 'frdspr3a.103'],
        "sound_roms": ['frsnd.u7', 'frsnd.u17', 'frsnd.u21', 'frsnd.u36'],
        "filename_hints": ['frankst'],
    },
    "maverick_the_movie": {
        "display": 'Maverick, The Movie',
        "family": 'mav',
        "manufacturer": 'Sega',
        "year": 1994,
        "dmd": '192x64',
        "game_roms": ['mavcpua.404'],
        "dmd_roms": ['mavdisp0.402', 'mavdisp3.402'],
        "sound_roms": ['mavu7.dat', 'mavu17.dat', 'mavu21.dat'],
        "filename_hints": ['mav'],
    },
    "apollo_13": {
        "display": 'Apollo 13',
        "family": 'apollo13',
        "manufacturer": 'Sega',
        "year": 1995,
        "dmd": '128x32',
        "game_roms": ['apolcpu.501'],
        "dmd_roms": ['a13dspa.500'],
        "sound_roms": ['apollo13.u7', 'apollo13.u17', 'apollo13.u21', 'apollo13.u36'],
        "filename_hints": ['apollo13'],
    },
    "batman_forever": {
        "display": 'Batman Forever',
        "family": 'batmanf',
        "manufacturer": 'Sega',
        "year": 1995,
        "dmd": '192x64',
        "game_roms": ['batnova.401'],
        "dmd_roms": ['bfdrom0a.401', 'bfdrom3a.401'],
        "sound_roms": ['bmfu7.bin', 'bmfu17.bin', 'bmfu21.bin'],
        "filename_hints": ['batmanf'],
    },
    "baywatch": {
        "display": 'Baywatch',
        "family": 'baywatch',
        "manufacturer": 'Sega',
        "year": 1995,
        "dmd": '192x64',
        "game_roms": ['baycpua.400'],
        "dmd_roms": ['bayrom0a.400', 'bayrom3a.400'],
        "sound_roms": ['bayw.u7', 'bayw.u17', 'bayw.u21'],
        "filename_hints": ['baywatch'],
    },
    "goldeneye": {
        "display": 'GoldenEye',
        "family": 'gldneye',
        "manufacturer": 'Sega',
        "year": 1996,
        "dmd": '128x32',
        "game_roms": ['bondcpu.404'],
        "dmd_roms": ['bondispa.400'],
        "sound_roms": ['bondu7.bin', 'bondu17.bin', 'bondu21.bin'],
        "filename_hints": ['gldneye'],
    },
    "id4_independence_day": {
        "display": 'ID4: Independence Day',
        "family": 'id4',
        "manufacturer": 'Sega',
        "year": 1996,
        "dmd": '128x32',
        "game_roms": ['id4cpu.202'],
        "dmd_roms": ['id4dspa.200'],
        "sound_roms": ['id4sndu7.512', 'id4sdu17.400', 'id4sdu21.400'],
        "filename_hints": ['id4'],
    },
    "twister": {
        "display": 'Twister',
        "family": 'twst',
        "manufacturer": 'Sega',
        "year": 1996,
        "dmd": '128x32',
        "game_roms": ['twstcpu.405'],
        "dmd_roms": ['twstdspa.400'],
        "sound_roms": [],
        "filename_hints": ['twst'],
    },
    "lost_world_jurassic_park": {
        "display": 'The Lost World: Jurassic Park',
        "family": 'jplstw22',
        "manufacturer": 'Sega',
        "year": 1997,
        "dmd": '128x32',
        "game_roms": ['jp2cpu.202'],
        "dmd_roms": ['jp2dspa.201'],
        "sound_roms": [],
        "filename_hints": ['jplstw22'],
    },
    "space_jam": {
        "display": 'Space Jam',
        "family": 'spacejam',
        "manufacturer": 'Sega',
        "year": 1997,
        "dmd": '128x32',
        "game_roms": ['jamcpu.300'],
        "dmd_roms": ['jamdspa.300'],
        "sound_roms": [],
        "filename_hints": ['spacejam'],
    },
    "star_wars_trilogy_special_edition": {
        "display": 'The Star Wars Trilogy Special Edition',
        "family": 'swtril43',
        "manufacturer": 'Sega',
        "year": 1997,
        "dmd": '128x32',
        "game_roms": ['swcpu.403'],
        "dmd_roms": ['swsedspa.400'],
        "sound_roms": [],
        "filename_hints": ['swtril43'],
    },
    "starship_troopers": {
        "display": 'Starship Troopers',
        "family": 'startrp',
        "manufacturer": 'Sega',
        "year": 1997,
        "dmd": '128x32',
        "game_roms": ['sstcpu.201'],
        "dmd_roms": ['sstdspa.200'],
        "sound_roms": ['u7_b130.512', 'u17_152a.040', 'u21_0291.040', 'u36_95a7.040'],
        "filename_hints": ['startrp'],
    },
    "x_files": {
        "display": 'The X-Files',
        "family": 'xfiles',
        "manufacturer": 'Sega',
        "year": 1997,
        "dmd": '128x32',
        "game_roms": ['xfcpu.303'],
        "dmd_roms": ['xfildspa.300'],
        "sound_roms": [],
        "filename_hints": ['xfiles'],
    },
    "godzilla": {
        "display": 'Godzilla',
        "family": 'godzilla',
        "manufacturer": 'Sega',
        "year": 1998,
        "dmd": '128x32',
        "game_roms": ['gdzcpu.205'],
        "dmd_roms": ['gzdspa.200'],
        "sound_roms": ['gdzu7.100', 'gdzu17.100', 'gdzu21.100', 'gdzu36.100', 'gdzu37.100'],
        "filename_hints": ['godzilla'],
    },
    "golden_cue": {
        "display": 'Golden Cue',
        "family": 'goldcue',
        "manufacturer": 'Sega',
        "year": 1998,
        "dmd": '128x32',
        "game_roms": ['gc_cpu.210'],
        "dmd_roms": ['gc_disp.u12'],
        "sound_roms": ['gc_sound.u7', 'gc_sound.u17', 'gc_sound.u21', 'gc_sound.u36'],
        "filename_hints": ['goldcue'],
    },
    "lost_in_space": {
        "display": 'Lost in Space',
        "family": 'lostspc',
        "manufacturer": 'Sega',
        "year": 1998,
        "dmd": '128x32',
        "game_roms": ['liscpu.101'],
        "dmd_roms": ['lisdspa.102'],
        "sound_roms": [],
        "filename_hints": ['lostspc'],
    },
    "viper_night_drivin": {
        "display": "Viper Night Drivin'",
        "family": 'viprsega',
        "manufacturer": 'Sega',
        "year": 1998,
        "dmd": '128x32',
        "game_roms": ['vipcpu.201'],
        "dmd_roms": ['vipdspa.201'],
        "sound_roms": ['vpru7.dat', 'vpru17.dat', 'vpru21.dat', 'vpru36.dat', 'vpru37.dat'],
        "filename_hints": ['viprsega'],
    },
    "harley_davidson": {
        "display": 'Harley-Davidson',
        "family": 'harl',
        "manufacturer": 'Sega',
        "year": 1999,
        "dmd": '128x32',
        "game_roms": ['harcpu.103'],
        "dmd_roms": ['hddisps.104'],
        "sound_roms": [],
        "filename_hints": ['harl'],
    },
    "south_park": {
        "display": 'South Park',
        "family": 'sprk',
        "manufacturer": 'Sega',
        "year": 1999,
        "dmd": '128x32',
        "game_roms": ['spkcpu.103'],
        "dmd_roms": ['spdspa.101'],
        "sound_roms": ['spku7.101', 'spku17.100', 'spku21.100', 'spku36.100', 'spku37.100'],
        "filename_hints": ['sprk'],
    },
    "sharkeys_shootout": {
        "display": "Sharkey's Shootout",
        "family": 'shrkysht',
        "manufacturer": 'Stern',
        "year": 2000,
        "dmd": '128x32',
        "game_roms": ['sscpu.211'],
        "dmd_roms": ['ssdispa.201'],
        "sound_roms": [],
        "filename_hints": ['shrkysht'],
    },
    "striker_xtreme": {
        "display": 'Striker Xtreme',
        "family": 'strikext',
        "manufacturer": 'Stern',
        "year": 2000,
        "dmd": '128x32',
        "game_roms": ['sxcpua.102'],
        "dmd_roms": ['sxdispa.103'],
        "sound_roms": ['sxsnda.u7', 'sxsnda.u17', 'sxsnda.u21', 'sxsnda.u36', 'sxsnda.u37'],
        "filename_hints": ['strikext'],
    },
    "austin_powers": {
        "display": 'Austin Powers',
        "family": 'austin',
        "manufacturer": 'Stern',
        "year": 2001,
        "dmd": '128x32',
        "game_roms": ['apcpu.302'],
        "dmd_roms": ['apdsp-a.300'],
        "sound_roms": [],
        "filename_hints": ['austin'],
    },
    "high_roller_casino": {
        "display": 'High Roller Casino',
        "family": 'hirolcas',
        "manufacturer": 'Stern',
        "year": 2001,
        "dmd": '128x32',
        "game_roms": ['hrccpu.300'],
        "dmd_roms": ['hrcdispa.300'],
        "sound_roms": [],
        "filename_hints": ['hirolcas'],
    },
    "monopoly": {
        "display": 'Monopoly',
        "family": 'monopoly',
        "manufacturer": 'Stern',
        "year": 2001,
        "dmd": '128x32',
        "game_roms": ['moncpu.320'],
        "dmd_roms": ['mondsp-a.301'],
        "sound_roms": ['mnsndu7.100', 'mnsndu17.100', 'mnsndu21.100', 'mnsndu36.100'],
        "filename_hints": ['monopoly'],
    },
    "nfl": {
        "display": 'NFL',
        "family": 'nfl',
        "manufacturer": 'Stern',
        "year": 2001,
        "dmd": '128x32',
        "game_roms": ['nfl_v101.cpu'],
        "dmd_roms": ['nfl_v102.dmd'],
        "sound_roms": ['nfl_v100.u7', 'nfl_v100.u17', 'nfl_v100.u21', 'nfl_v100.u36', 'nfl_v100.u37'],
        "filename_hints": ['nfl'],
    },
    "playboy": {
        "display": 'Playboy',
        "family": 'playboys',
        "manufacturer": 'Stern',
        "year": 2002,
        "dmd": '128x32',
        "game_roms": ['pbcpu.500'],
        "dmd_roms": ['pbdispa.500'],
        "sound_roms": [],
        "filename_hints": ['playboys'],
    },
    "rollercoaster_tycoon": {
        "display": 'RollerCoaster Tycoon',
        "family": 'rctycn',
        "manufacturer": 'Stern',
        "year": 2002,
        "dmd": '128x32',
        "game_roms": ['rctcpu.702'],
        "dmd_roms": ['rctdispa.701'],
        "sound_roms": [],
        "filename_hints": ['rctycn'],
    },
    "simpsons_pinball_party": {
        "display": 'The Simpsons Pinball Party',
        "family": 'simpprty',
        "manufacturer": 'Stern',
        "year": 2003,
        "dmd": '128x32',
        "game_roms": ['spp-cpu.500'],
        "dmd_roms": ['sppdispa.500'],
        "sound_roms": [],
        "filename_hints": ['simpprty'],
    },
    "terminator_3_rise_of_the_machines": {
        "display": 'Terminator 3: Rise of the Machines',
        "family": 'term3',
        "manufacturer": 'Stern',
        "year": 2003,
        "dmd": '128x32',
        "game_roms": ['t3cpu.400'],
        "dmd_roms": ['t3dispa.400'],
        "sound_roms": [],
        "filename_hints": ['term3'],
    },
    "elvis": {
        "display": 'Elvis',
        "family": 'elvis',
        "manufacturer": 'Stern',
        "year": 2004,
        "dmd": '128x32',
        "game_roms": ['Elvis_cpu_1.00.bin'],
        "dmd_roms": ['Elvis_display_1.00.bin'],
        "sound_roms": [],
        "filename_hints": ['elvis'],
    },
    "ripleys_believe_it_or_not": {
        "display": "Ripley's Believe It or Not!",
        "family": 'ripleys',
        "manufacturer": 'Stern',
        "year": 2004,
        "dmd": '128x32',
        "game_roms": ['ripcpu.320'],
        "dmd_roms": ['ripdispa.300'],
        "sound_roms": [],
        "filename_hints": ['ripleys'],
    },
    "lord_of_the_rings": {
        "display": 'The Lord of the Rings',
        "family": 'lotr',
        "manufacturer": 'Stern',
        "year": 2005,
        "dmd": '128x32',
        "game_roms": ['lotrcpua.a00'],
        "dmd_roms": ['lotrdspa.a00'],
        "sound_roms": [],
        "filename_hints": ['lotr'],
    },
    "sopranos": {
        "display": 'The Sopranos',
        "family": 'sopranos',
        "manufacturer": 'Stern',
        "year": 2005,
        "dmd": '128x32',
        "game_roms": ['sopcpua.500'],
        "dmd_roms": ['sopdspa.500'],
        "sound_roms": [],
        "filename_hints": ['sopranos'],
    },
    "dale_jr": {
        "display": 'Dale Jr.',
        "family": 'dalejr',
        "manufacturer": 'Stern',
        "year": 2006,
        "dmd": '128x32',
        "game_roms": ['dalecpu.500'],
        "dmd_roms": ['daledisp.500'],
        "sound_roms": [],
        "filename_hints": ['dalejr'],
    },
    "grand_prix": {
        "display": 'Grand Prix',
        "family": 'gprix',
        "manufacturer": 'Stern',
        "year": 2006,
        "dmd": '128x32',
        "game_roms": ['gpcpua.450'],
        "dmd_roms": ['gpdspa.400'],
        "sound_roms": [],
        "filename_hints": ['gprix'],
    },
    "nascar": {
        "display": 'NASCAR',
        "family": 'nascar',
        "manufacturer": 'Stern',
        "year": 2006,
        "dmd": '128x32',
        "game_roms": ['nascpua.450'],
        "dmd_roms": ['nasdspa.400'],
        "sound_roms": [],
        "filename_hints": ['nascar'],
    },
}
