"""Data East / early-Sega DMD-era game database.

Auto-generated from PinMAME ``src/wpc/degames.c`` (vpinball/pinmame):
every family whose machine type is ``de_mDEDMD{16,32,64}`` (i.e. has a
dot-matrix display, 1991+).  Per family we keep the PARENT romset's
ROM filenames; ``filename_hints`` is the romset family prefix, matched
against the user's zip basename (PinMAME zips are named
``<family>_<variant>.zip``).  Detection (see :mod:`.formats`) scores
each game by how many of its catalogued ROM names appear in the zip,
plus a hint bonus -- the same data-driven scheme the Williams plugin
uses, so adding titles needs no code change.

``manufacturer`` preserves the DE->Sega handover that happened on this
same hardware (Maverick/Frankenstein/Baywatch/Batman Forever shipped as
Sega).  ``dmd`` is the display resolution, which selects the DMD-ROM
animation decoder once that lands.
"""

GAME_DB = {
    "batman": {
        "display": 'Batman',
        "family": 'btmn',
        "manufacturer": 'Data East',
        "year": 1991,
        "dmd": '128x16',
        "game_roms": ['batcpub5.103', 'batcpuc5.103'],
        "dmd_roms": ['batdsp.102'],
        "sound_roms": ['batman.u7', 'batman.u17', 'batman.u21'],
        "filename_hints": ['btmn'],
    },
    "checkpoint": {
        "display": 'Checkpoint',
        "family": 'ckpt',
        "manufacturer": 'Data East',
        "year": 1991,
        "dmd": '128x16',
        "game_roms": ['chkpntb5.107', 'chkpntc5.107'],
        "dmd_roms": ['chkpntds.512'],
        "sound_roms": ['chkpntf7.rom', 'chkpntf6.rom', 'chkpntf5.rom'],
        "filename_hints": ['ckpt'],
    },
    "teenage_mutant_ninja_turtles": {
        "display": 'Teenage Mutant Ninja Turtles',
        "family": 'tmnt',
        "manufacturer": 'Data East',
        "year": 1991,
        "dmd": '128x16',
        "game_roms": ['tmntb5a.104', 'tmntc5a.104'],
        "dmd_roms": ['tmntdsp.104'],
        "sound_roms": ['tmntf7.rom', 'tmntf6.rom', 'tmntf4.rom'],
        "filename_hints": ['tmnt'],
    },
    "aaron_spelling": {
        "display": 'Aaron Spelling',
        "family": 'aar',
        "manufacturer": 'Data East',
        "year": 1992,
        "dmd": '128x32',
        "game_roms": ['as512cpu.bin'],
        "dmd_roms": ['asdspu12.bin', 'asdspu14.bin'],
        "sound_roms": ['assndu7.bin', 'assndu17.bin', 'assndu21.bin'],
        "filename_hints": ['aar'],
    },
    "hook": {
        "display": 'Hook',
        "family": 'hook',
        "manufacturer": 'Data East',
        "year": 1992,
        "dmd": '128x16',
        "game_roms": ['hokcpua.408'],
        "dmd_roms": ['hokdspa.401'],
        "sound_roms": ['hooksnd.u7', 'hook-voi.u17', 'hook-voi.u21'],
        "filename_hints": ['hook'],
    },
    "lethal_weapon_3": {
        "display": 'Lethal Weapon 3',
        "family": 'lw3',
        "manufacturer": 'Data East',
        "year": 1992,
        "dmd": '128x32',
        "game_roms": ['lw3cpuu.208'],
        "dmd_roms": ['lw3drom1.a26', 'lw3drom0.a26'],
        "sound_roms": ['lw3u7.dat', 'lw3u17.dat', 'lw3u21.dat'],
        "filename_hints": ['lw3'],
    },
    "michael_jordan": {
        "display": 'Michael Jordan',
        "family": 'mj',
        "manufacturer": 'Data East',
        "year": 1992,
        "dmd": '128x32',
        "game_roms": ['MJcpuc5.bin'],
        "dmd_roms": ['MJdsp0.bin'],
        "sound_roms": ['MJsndu7.bin', 'MJsndu17.bin', 'MJsndu21.bin'],
        "filename_hints": ['mj'],
    },
    "star_trek_25th_anniversary": {
        "display": 'Star Trek 25th Anniversary',
        "family": 'trek',
        "manufacturer": 'Data East',
        "year": 1992,
        "dmd": '128x16',
        "game_roms": ['trekcpuu.201'],
        "dmd_roms": ['trekdspa.109'],
        "sound_roms": ['trek.u7', 'trek.u17', 'trek.u21'],
        "filename_hints": ['trek'],
    },
    "adventures_of_rocky_and_bullwinkle_and_friends": {
        "display": 'The Adventures of Rocky and Bullwinkle and Friends',
        "family": 'rab',
        "manufacturer": 'Data East',
        "year": 1993,
        "dmd": '128x32',
        "game_roms": ['rabcpua.320'],
        "dmd_roms": ['rbdspa.300'],
        "sound_roms": ['rab.u7', 'rab.u17', 'rab.u21'],
        "filename_hints": ['rab'],
    },
    "jurassic_park": {
        "display": 'Jurassic Park',
        "family": 'jupk',
        "manufacturer": 'Data East',
        "year": 1993,
        "dmd": '128x32',
        "game_roms": ['jpcpua.513'],
        "dmd_roms": ['jpdspa.510'],
        "sound_roms": ['jpu7.dat', 'jpu17.dat', 'jpu21.dat'],
        "filename_hints": ['jupk'],
    },
    "last_action_hero": {
        "display": 'Last Action Hero',
        "family": 'lah',
        "manufacturer": 'Data East',
        "year": 1993,
        "dmd": '128x32',
        "game_roms": ['lahcpua.112'],
        "dmd_roms": ['lahdispa.106'],
        "sound_roms": ['lahsnd.u7', 'lahsnd.u17', 'lahsnd.u21'],
        "filename_hints": ['lah'],
    },
    "tales_from_the_crypt": {
        "display": 'Tales from the Crypt',
        "family": 'tftc',
        "manufacturer": 'Data East',
        "year": 1993,
        "dmd": '128x32',
        "game_roms": ['tftccpua.303'],
        "dmd_roms": ['tftcdspa.301'],
        "sound_roms": ['sndu7.dat', 'sndu17.dat', 'sndu21.dat'],
        "filename_hints": ['tftc'],
    },
    "frankenstein_mary_shelleys": {
        "display": "Frankenstein, Mary Shelley's",
        "family": 'frankst',
        "manufacturer": 'Sega',
        "year": 1994,
        "dmd": '192x64',
        "game_roms": ['franka.103'],
        "dmd_roms": ['frdspr0a.103', 'frdspr3a.103'],
        "sound_roms": ['frsnd.u7', 'frsnd.u17', 'frsnd.u21', 'frsnd.u36'],
        "filename_hints": ['frankst'],
    },
    "guns_n_roses": {
        "display": "Guns N' Roses",
        "family": 'gnr',
        "manufacturer": 'Data East',
        "year": 1994,
        "dmd": '128x32',
        "game_roms": ['gnrcpua.300'],
        "dmd_roms": ['gnrdispa.300'],
        "sound_roms": ['gnru7.snd', 'gnru17.snd', 'gnru21.snd', 'gnru36.snd', 'gnru37.snd'],
        "filename_hints": ['gnr'],
    },
    "maverick_the_movie": {
        "display": 'Maverick, The Movie',
        "family": 'mav',
        "manufacturer": 'Sega',
        "year": 1994,
        "dmd": '192x64',
        "game_roms": ['mavcpua.404'],
        "dmd_roms": ['mavdisp0.402', 'mavdisp3.402'],
        "sound_roms": ['mavu7.dat', 'mavu17.dat', 'mavu21.dat'],
        "filename_hints": ['mav'],
    },
    "tommy_pinball_wizard_the_whos": {
        "display": "Tommy Pinball Wizard, The Who's",
        "family": 'tomy',
        "manufacturer": 'Data East',
        "year": 1994,
        "dmd": '128x32',
        "game_roms": ['tomcpua.400'],
        "dmd_roms": ['tommydva.400'],
        "sound_roms": ['tommysnd.u7', 'tommysnd.u17', 'tommysnd.u21', 'tommysnd.u36', 'tommysnd.u37'],
        "filename_hints": ['tomy'],
    },
    "wwf_royal_rumble": {
        "display": 'WWF Royal Rumble',
        "family": 'wwfr',
        "manufacturer": 'Data East',
        "year": 1994,
        "dmd": '128x32',
        "game_roms": ['wwfcpua.106'],
        "dmd_roms": ['wwfdispa.102'],
        "sound_roms": ['wfsndu7.512', 'wfsndu17.400', 'wfsndu21.400', 'wfsndu36.400'],
        "filename_hints": ['wwfr'],
    },
    "batman_forever": {
        "display": 'Batman Forever',
        "family": 'batmanf',
        "manufacturer": 'Sega',
        "year": 1995,
        "dmd": '192x64',
        "game_roms": ['batnova.401'],
        "dmd_roms": ['bfdrom0a.401', 'bfdrom3a.401'],
        "sound_roms": ['bmfu7.bin', 'bmfu17.bin', 'bmfu21.bin'],
        "filename_hints": ['batmanf'],
    },
    "baywatch": {
        "display": 'Baywatch',
        "family": 'baywatch',
        "manufacturer": 'Sega',
        "year": 1995,
        "dmd": '192x64',
        "game_roms": ['baycpua.400'],
        "dmd_roms": ['bayrom0a.400', 'bayrom3a.400'],
        "sound_roms": ['bayw.u7', 'bayw.u17', 'bayw.u21'],
        "filename_hints": ['baywatch'],
    },
    "star_wars": {
        "display": 'Star Wars',
        "family": 'stwr',
        "manufacturer": 'Data East',
        "year": 2012,
        "dmd": '128x32',
        "game_roms": ['starcpua.104'],
        "dmd_roms": ['sw4mrom.a15'],
        "sound_roms": ['s-wars.u7', 's-wars.u17', 's-wars.u21'],
        "filename_hints": ['stwr'],
    },
}
